/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import entity.achat;
import entity.midicament;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import work.tools;

/**
 *
 * @author choqib
 */
public class frmAchatretour extends javax.swing.JFrame {
midicament m= new midicament();
    achat a=new achat();
int i=0;


  boolean row_Is_Selected = false;
    int index;
    DefaultTableModel model;
    String nbc=(a.getAutoNumber());
    /**
     * Creates new form frmAchat
     */
    public frmAchatretour() {
        
        
        //prixpara.setEditable(false);
    
        
 this.setUndecorated(false);
        this.setAlwaysOnTop(false);
       this.setResizable(false);
        this.setVisible(true);
        
    
        initComponents();
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        int x=(int) tk.getScreenSize().getWidth();
        int y=(int) tk.getScreenSize().getHeight();
        this.setSize(x,y );
         
 stabmed.setVisible(false);
 stabpara.setVisible(false);
        tabmed.setVisible(false);
         tabpara.setVisible(false);
         tabforn.setVisible(false);
         stabforn.setVisible(false);
         
          nb.setText(a.getAutoNumber());
          //String nbc=(a.getAutoNumber());
          nbf.setText(nbc);
          //a.getAllRows(tabcmd);
       
      
       
           }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroup = new javax.swing.ButtonGroup();
        btngroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdof = new javax.swing.JRadioButton();
        rdobl = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        stabforn = new javax.swing.JScrollPane();
        tabforn = new javax.swing.JTable();
        nbf = new javax.swing.JTextField();
        mantant = new javax.swing.JTextField();
        txt = new javax.swing.JLabel();
        ppa = new javax.swing.JTextField();
        stabmed = new javax.swing.JScrollPane();
        tabmed = new javax.swing.JTable();
        med = new javax.swing.JTextField();
        prixmed = new javax.swing.JTextField();
        qtemed = new javax.swing.JTextField();
        nlot = new javax.swing.JTextField();
        shp = new javax.swing.JTextField();
        marge = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabcmd = new javax.swing.JTable();
        para = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        stabpara = new javax.swing.JScrollPane();
        tabpara = new javax.swing.JTable();
        prixpara = new javax.swing.JTextField();
        qtepara = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btnsup = new javax.swing.JButton();
        btnvalid = new javax.swing.JButton();
        nb = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        forn = new javax.swing.JTextField();
        date1 = new com.toedter.calendar.JDateChooser();
        dateexp = new com.toedter.calendar.JDateChooser();
        ug = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        prixVente = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Fournesseurs");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 110, 176, 21);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("N° Cmd");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 110, 60, 21);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Type d'Achat");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(870, 110, 99, 21);

        rdof.setBackground(new java.awt.Color(255, 255, 255));
        rdof.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdof.setMnemonic('F');
        rdof.setSelected(true);
        rdof.setText("Facteure");
        getContentPane().add(rdof);
        rdof.setBounds(850, 130, 80, 40);

        rdobl.setBackground(new java.awt.Color(255, 255, 255));
        rdobl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdobl.setMnemonic('b');
        rdobl.setText("BL");
        getContentPane().add(rdobl);
        rdobl.setBounds(930, 130, 60, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("N°  Facture");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(580, 110, 99, 21);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Mantant Facture");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(690, 110, 120, 21);

        stabforn.setBackground(new java.awt.Color(255, 255, 255));
        stabforn.setForeground(new java.awt.Color(255, 255, 255));

        tabforn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabforn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabfornKeyPressed(evt);
            }
        });
        stabforn.setViewportView(tabforn);
        if (tabforn.getColumnModel().getColumnCount() > 0) {
            tabforn.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(stabforn);
        stabforn.setBounds(250, 160, 320, 110);

        nbf.setEditable(false);
        nbf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(nbf);
        nbf.setBounds(580, 130, 80, 30);

        mantant.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        mantant.setForeground(new java.awt.Color(0, 153, 0));
        getContentPane().add(mantant);
        mantant.setBounds(670, 130, 180, 30);

        txt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txt.setText("________Les Achats Details____________________________________________________________________________________________________________________________");
        txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKeyTyped(evt);
            }
        });
        getContentPane().add(txt);
        txt.setBounds(10, 180, 1360, 20);

        ppa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ppa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ppaKeyReleased(evt);
            }
        });
        getContentPane().add(ppa);
        ppa.setBounds(560, 270, 100, 30);

        tabmed.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabmed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Désignation", "Forme", "Dosage"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabmed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabmedKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabmedKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tabmedKeyTyped(evt);
            }
        });
        stabmed.setViewportView(tabmed);
        if (tabmed.getColumnModel().getColumnCount() > 0) {
            tabmed.getColumnModel().getColumn(0).setResizable(false);
            tabmed.getColumnModel().getColumn(1).setResizable(false);
            tabmed.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(stabmed);
        stabmed.setBounds(30, 300, 510, 130);

        med.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medActionPerformed(evt);
            }
        });
        med.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                medKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                medKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                medKeyTyped(evt);
            }
        });
        getContentPane().add(med);
        med.setBounds(30, 270, 510, 30);

        prixmed.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prixmed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prixmedKeyReleased(evt);
            }
        });
        getContentPane().add(prixmed);
        prixmed.setBounds(700, 270, 80, 30);

        qtemed.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        qtemed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtemedKeyReleased(evt);
            }
        });
        getContentPane().add(qtemed);
        qtemed.setBounds(789, 270, 50, 30);

        nlot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nlot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nlotKeyReleased(evt);
            }
        });
        getContentPane().add(nlot);
        nlot.setBounds(30, 340, 100, 30);

        shp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        shp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shpActionPerformed(evt);
            }
        });
        shp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                shpKeyReleased(evt);
            }
        });
        getContentPane().add(shp);
        shp.setBounds(160, 340, 100, 30);

        marge.setEditable(false);
        marge.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(marge);
        marge.setBounds(280, 340, 70, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Date d'EXP");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 310, 80, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("PPA sans SHP");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(570, 250, 100, 15);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Désignation / Nom de Produit");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(50, 250, 230, 14);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Prix d'Achat");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(700, 240, 80, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Qte");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(790, 240, 50, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("N° Lot");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(40, 310, 50, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("SHP");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(170, 310, 70, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Marge");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(280, 310, 70, 30);

        tabcmd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° Cmd", "Désignation", "PPA", "Date d'Exp", "N° Lot", "QTE", "Prix Achat ", "Prix Vent", "Shp", "Marge", "Fournisseure", "N° Facture", "UG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabcmd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabcmdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabcmd);
        if (tabcmd.getColumnModel().getColumnCount() > 0) {
            tabcmd.getColumnModel().getColumn(0).setResizable(false);
            tabcmd.getColumnModel().getColumn(1).setResizable(false);
            tabcmd.getColumnModel().getColumn(2).setResizable(false);
            tabcmd.getColumnModel().getColumn(3).setResizable(false);
            tabcmd.getColumnModel().getColumn(4).setResizable(false);
            tabcmd.getColumnModel().getColumn(5).setResizable(false);
            tabcmd.getColumnModel().getColumn(6).setResizable(false);
            tabcmd.getColumnModel().getColumn(7).setResizable(false);
            tabcmd.getColumnModel().getColumn(8).setResizable(false);
            tabcmd.getColumnModel().getColumn(9).setResizable(false);
            tabcmd.getColumnModel().getColumn(10).setResizable(false);
            tabcmd.getColumnModel().getColumn(11).setResizable(false);
            tabcmd.getColumnModel().getColumn(12).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(32, 470, 1320, 290);
        getContentPane().add(para);
        para.setBounds(940, 270, 410, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Désignation / Nom de Produit");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(950, 250, 230, 14);

        tabpara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Désignation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stabpara.setViewportView(tabpara);
        if (tabpara.getColumnModel().getColumnCount() > 0) {
            tabpara.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(stabpara);
        stabpara.setBounds(940, 300, 410, 140);

        prixpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixparaActionPerformed(evt);
            }
        });
        getContentPane().add(prixpara);
        prixpara.setBounds(940, 340, 80, 30);
        getContentPane().add(qtepara);
        qtepara.setBounds(1030, 340, 50, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Prix");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(940, 310, 70, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Qte");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(1030, 310, 50, 30);

        btnadd.setMnemonic('i');
        btnadd.setText("Insérie line Cmd");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd);
        btnadd.setBounds(70, 440, 180, 23);

        btnsup.setMnemonic('s');
        btnsup.setText("Supprimer Line Cmd");
        btnsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupActionPerformed(evt);
            }
        });
        getContentPane().add(btnsup);
        btnsup.setBounds(263, 440, 180, 23);

        btnvalid.setMnemonic('v');
        btnvalid.setText("Validation");
        btnvalid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvalidActionPerformed(evt);
            }
        });
        getContentPane().add(btnvalid);
        btnvalid.setBounds(453, 440, 200, 23);

        nb.setEditable(false);
        nb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(nb);
        nb.setBounds(29, 130, 60, 30);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Date d'Achat");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(130, 110, 99, 21);

        forn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        forn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fornKeyReleased(evt);
            }
        });
        getContentPane().add(forn);
        forn.setBounds(249, 130, 320, 30);

        date1.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(date1);
        date1.setBounds(101, 130, 130, 30);

        dateexp.setDateFormatString("yyyy-MM-dd");
        dateexp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateexpKeyReleased(evt);
            }
        });
        getContentPane().add(dateexp);
        dateexp.setBounds(360, 340, 130, 30);

        ug.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ugKeyReleased(evt);
            }
        });
        getContentPane().add(ug);
        ug.setBounds(500, 340, 50, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Prix Vent");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(570, 320, 70, 15);

        prixVente.setEditable(false);
        prixVente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prixVente.setForeground(new java.awt.Color(0, 153, 0));
        prixVente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prixVenteKeyReleased(evt);
            }
        });
        getContentPane().add(prixVente);
        prixVente.setBounds(560, 340, 110, 30);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("U G");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(500, 320, 34, 15);

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/back1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(100, 0, 97, 70);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/ch17.png"))); // NOI18N
        jPanel1.add(jLabel32);
        jLabel32.setBounds(470, 0, 90, 70);

        jLabel33.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Retour Commande");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(580, 14, 360, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1380, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
btnsup.setEnabled(false);
btnvalid.setEnabled(false);
//panevalid.setVisible(false);
forn.requestFocus();
Calendar clndr =Calendar.getInstance();
 date1.setCalendar(clndr);
 dateexp.setCalendar(clndr);
 btngroup2.add(rdobl);
 btngroup2.add(rdof);
 tabcmd.setAutoResizeMode(tabcmd.AUTO_RESIZE_OFF);
 TableColumn col=tabcmd.getColumnModel().getColumn(0);
 col.setPreferredWidth(50);
 col=tabcmd.getColumnModel().getColumn(1);
 col.setPreferredWidth(300);
  col=tabcmd.getColumnModel().getColumn(2);
 col.setPreferredWidth(80);
  col=tabcmd.getColumnModel().getColumn(3);
 col.setPreferredWidth(100);
  col=tabcmd.getColumnModel().getColumn(4);
 col.setPreferredWidth(80);
  col=tabcmd.getColumnModel().getColumn(5);
 col.setPreferredWidth(50);
  col=tabcmd.getColumnModel().getColumn(6);
 col.setPreferredWidth(100);
  col=tabcmd.getColumnModel().getColumn(7);
 col.setPreferredWidth(100);
  col=tabcmd.getColumnModel().getColumn(8);
 col.setPreferredWidth(50);
  col=tabcmd.getColumnModel().getColumn(9);
 col.setPreferredWidth(60);
  col=tabcmd.getColumnModel().getColumn(10);
 col.setPreferredWidth(200);
  col=tabcmd.getColumnModel().getColumn(11);
 col.setPreferredWidth(100);
  col=tabcmd.getColumnModel().getColumn(12);
 col.setPreferredWidth(50);
   tabcmd.getTableHeader().setBackground(new Color(0,0,100));
tabcmd.getTableHeader().setForeground(Color.white);
tabcmd.setShowGrid(false);
tabcmd.setShowVerticalLines(false);
   tabcmd.setColumnSelectionAllowed(false);
    tabcmd.setRowSelectionAllowed(true);
    tabcmd.setSelectionBackground(Color.red);
       
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void medKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_medKeyReleased
if(med.getText().isEmpty()){}
else{
        tabmed.getTableHeader().setBackground(new Color(0,0,100));
tabmed.getTableHeader().setForeground(Color.white);
tabmed.setShowGrid(false);
tabmed.setShowVerticalLines(false);
   tabmed.setColumnSelectionAllowed(false);
    tabmed.setRowSelectionAllowed(true);
    tabmed.setSelectionBackground(Color.green);  
       
    
        m.getCustomRows("select nom,forme,dosage from produit where nom like'"+med.getText()+"%';", tabmed);
        tabmed.setVisible(true);
stabmed.setVisible(true);

if(evt.getKeyCode()==KeyEvent.VK_DOWN){
tabmed.requestFocus();
}


} // TODO add your handling code here:
    }//GEN-LAST:event_medKeyReleased

    private void medKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_medKeyPressed


          // TODO add your handling code here:
    }//GEN-LAST:event_medKeyPressed

    private void tabmedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabmedKeyReleased
     if(evt.getKeyCode()==KeyEvent.VK_ENTER){
 int row =tabmed.getSelectedRow();
 String strno=tabmed.getValueAt(row-1, 0).toString();
  String strno1=tabmed.getValueAt(row-1, 1).toString();
   String strno2=tabmed.getValueAt(row-1, 2).toString();
 med.setText(strno+"  "+strno1+"  "+strno2);
 ppa.requestFocus();
 tabmed.setVisible(false);
 stabmed.setVisible(false);
 }  // TODO add your handling code here:
    }//GEN-LAST:event_tabmedKeyReleased

    private void medKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_medKeyTyped
 //        // TODO add your handling code here:
    }//GEN-LAST:event_medKeyTyped

    private void tabmedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabmedKeyPressed

// TODO add your handling code here:
    }//GEN-LAST:event_tabmedKeyPressed

    private void tabmedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabmedKeyTyped
// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_tabmedKeyTyped

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        
        if((prixmed.getText().isEmpty())|(ppa.getText().isEmpty())|
                (nlot.getText().isEmpty())|(qtemed.getText().isEmpty())|(med.getText().isEmpty())|
                (marge.getText().isEmpty())|(shp.getText().isEmpty())){
            tools.msgBox("SVP countinue touts les champs");}
        else{
        a.setId((Integer.parseInt(nb.getText())));
         SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
       String HDate = String.valueOf(f.format( dateexp.getDate() ));
      a.setDate(HDate);
        a.setNbf(((nbf.getText())));
        a.setMge((marge.getText()));
        
        a.setNlot(((nlot.getText())));
        a.setPht((Float.parseFloat(prixmed.getText())));
        a.setPpa((Float.parseFloat(ppa.getText())));
        a.setPvent((Float.parseFloat(prixVente.getText())));
        a.setQte((Integer.parseInt(qtemed.getText())));
        a.setNom(med.getText());
        a.setNom_forn(forn.getText());
        a.setUg(Integer.parseInt(ug.getText()));
       
        a.add();
        a.getAllRows(tabcmd);
        tabcmd.getTableHeader().setBackground(new Color(0,0,100));
tabcmd.getTableHeader().setForeground(Color.white);
tabcmd.setShowGrid(false);
tabcmd.setShowVerticalLines(false);
   tabcmd.setColumnSelectionAllowed(false);
    tabcmd.setRowSelectionAllowed(true);
    tabcmd.setSelectionBackground(Color.red);  
    int count=tabcmd.getRowCount();

        tools.clearText(this);
        Calendar clndr =Calendar.getInstance();
        date1.setCalendar(clndr);
        nb.setText(a.getAutoNumber());
        nbf.setText(nbc);
       forn.setText(a.getNameByValue(nbc));
        
   float stock=0;
int q;float som;
     for(int i=0;i<count;i++)
{
  //  tools.msgBox("hello");
  q= Integer.parseInt(tabcmd.getValueAt(i,5).toString())-Integer.parseInt(tabcmd.getValueAt(i,12).toString());
 //q=q-((Integer.parseInt(qtemed.getText())));
som= Float.parseFloat(tabcmd.getValueAt(i,6).toString());
stock=stock+(q*som);   
}    


String s=String.valueOf(stock);
s=s+"   DA";
mantant.setText(s);
med.requestFocus();
forn.setEnabled(false);
btnvalid.setEnabled(true);
}
       
        
        
        
        
       
                                       // TODO add your handling code here:
    }//GEN-LAST:event_btnaddActionPerformed

    private void medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medActionPerformed

    private void fornKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fornKeyReleased
      tabforn.setVisible(true);
      stabforn.setVisible(true);
       tabforn.getTableHeader().setBackground(new Color(0,0,100));
tabforn.getTableHeader().setForeground(Color.white);
tabforn.setShowGrid(false);
tabforn.setShowVerticalLines(false);
   tabforn.setColumnSelectionAllowed(false);
    tabforn.setRowSelectionAllowed(true);
    tabforn.setSelectionBackground(Color.red);
      a.getCustomRows("select nom from fournisseur where nom LIKE'"+forn.getText()+"%'", tabforn);
      if(evt.getKeyCode()==KeyEvent.VK_DOWN){
tabforn.requestFocus();
}
      
       //AutoCompleteDecorator.decorate(comboforn);
       
      
    }//GEN-LAST:event_fornKeyReleased

    private void combofornKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combofornKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_combofornKeyTyped

    private void txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeyTyped

    private void prixparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixparaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixparaActionPerformed

    private void btnsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupActionPerformed
a.setId(Integer.parseInt(nb.getText()));
a.delete();
a.getAllRows(tabcmd);  
int count=tabcmd.getRowCount();
float stock=0;
int q;float som;
for(int i=0;i<count;i++)
{
  //  tools.msgBox("hello");
  q= Integer.parseInt(tabcmd.getValueAt(i,5).toString())-Integer.parseInt(tabcmd.getValueAt(i,12).toString());
som= Float.parseFloat(tabcmd.getValueAt(i,6).toString());
stock=stock+(q*som);   
}
med.requestFocus();
if(stock==0.0){forn.setEnabled(true);forn.requestFocus();
String s=String.valueOf(stock);
s=s+"   DA";
mantant.setText(s);
btnadd.setEnabled(true);
btnvalid.setEnabled(false);
btnsup.setEnabled(false);}
String s=String.valueOf(stock);
s=s+"   DA";
mantant.setText(s);
btnadd.setEnabled(true);
btnsup.setEnabled(false);

// TODO add your handling code here:
    }//GEN-LAST:event_btnsupActionPerformed

    private void tabcmdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabcmdMouseClicked
btnadd.setEnabled(false);
int row=tabcmd.getSelectedRow();
String strno=tabcmd.getValueAt(row, 0).toString(); 
nb.setText(strno);
btnsup.setEnabled(true);
// TODO add your handling code here:
    }//GEN-LAST:event_tabcmdMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
      btnadd.setEnabled(true);
      btnsup.setEnabled(false);
nb.setText(a.getAutoNumber());
med.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void tabfornKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabfornKeyPressed
 if(evt.getKeyCode()==KeyEvent.VK_ENTER){
 int r =tabforn.getSelectedRow();
 String str=tabforn.getValueAt(r, 0).toString();
 forn.setText(str);
 ppa.requestFocus();
 tabforn.setVisible(false);
 stabforn.setVisible(false);
 med.requestFocus();}
    }//GEN-LAST:event_tabfornKeyPressed

    private void prixmedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prixmedKeyReleased
if(evt.getKeyCode()==KeyEvent.VK_ENTER){
   qtemed.requestFocus();
   }
        float marge ;
 marge=(((Float.parseFloat(ppa.getText()))-(Float.parseFloat(prixmed.getText())))/(Float.parseFloat(prixmed.getText())))*100;
 DecimalFormat dtime = new DecimalFormat("0.00"); 
 marge =Float.parseFloat(dtime.format(marge));
 //marge=Float.parseFloat(new FloatFormat("##.####").format(marge));
 this.marge.setText(String.valueOf(marge)+"%"); 
  // TODO add your handling code here:
    }//GEN-LAST:event_prixmedKeyReleased

    private void shpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shpActionPerformed
  
    }//GEN-LAST:event_shpActionPerformed

    private void prixVenteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prixVenteKeyReleased
   // TODO add your handling code here:
    }//GEN-LAST:event_prixVenteKeyReleased

    private void shpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_shpKeyReleased
     float pven=((Float.parseFloat(ppa.getText()))+(Float.parseFloat(shp.getText())));
   prixVente.setText(String.valueOf(pven));
   if(evt.getKeyCode()==KeyEvent.VK_ENTER){
   dateexp.requestFocus();
   } // TODO add your handling code here:
    }//GEN-LAST:event_shpKeyReleased

    private void ppaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ppaKeyReleased
if(evt.getKeyCode()==KeyEvent.VK_ENTER){
   prixmed.requestFocus();
   }        // TODO add your handling code here:
    }//GEN-LAST:event_ppaKeyReleased

    private void nlotKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nlotKeyReleased
if(evt.getKeyCode()==KeyEvent.VK_ENTER){
   shp.requestFocus();
   }         // TODO add your handling code here:
    }//GEN-LAST:event_nlotKeyReleased

    private void dateexpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateexpKeyReleased
if(evt.getKeyCode()==KeyEvent.VK_ENTER){
   ug.requestFocus();
   }         // TODO add your handling code here:
    }//GEN-LAST:event_dateexpKeyReleased

    private void ugKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ugKeyReleased
if(evt.getKeyCode()==KeyEvent.VK_ENTER){
  
     if((prixmed.getText().isEmpty())|(ppa.getText().isEmpty())|
                (nlot.getText().isEmpty())|(qtemed.getText().isEmpty())|(med.getText().isEmpty())|
                (marge.getText().isEmpty())|(shp.getText().isEmpty())){
            tools.msgBox("SVP countinue touts les champs");}
        else{
        a.setId((Integer.parseInt(nb.getText())));
         SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
       String HDate = String.valueOf(f.format( dateexp.getDate() ));
      a.setDate(HDate);
        a.setNbf(((nbf.getText())));
        a.setMge((marge.getText()));
        
        a.setNlot(((nlot.getText())));
        a.setPht((Float.parseFloat(prixmed.getText())));
        a.setPpa((Float.parseFloat(ppa.getText())));
        a.setPvent((Float.parseFloat(prixVente.getText())));
        a.setQte((Integer.parseInt(qtemed.getText())));
        a.setNom(med.getText());
        a.setNom_forn(forn.getText());
        a.setUg(Integer.parseInt(ug.getText()));
       
        a.add();
        a.getAllRows(tabcmd);
        tabcmd.getTableHeader().setBackground(new Color(0,0,100));
tabcmd.getTableHeader().setForeground(Color.white);
tabcmd.setShowGrid(false);
tabcmd.setShowVerticalLines(false);
   tabcmd.setColumnSelectionAllowed(false);
    tabcmd.setRowSelectionAllowed(true);
    tabcmd.setSelectionBackground(Color.red);  
    int count=tabcmd.getRowCount();

        tools.clearText(this);
        Calendar clndr =Calendar.getInstance();
        date1.setCalendar(clndr);
        nb.setText(a.getAutoNumber());
        nbf.setText(nbc);
       forn.setText(a.getNameByValue(nbc));
        
   float stock=0;
int q;float som;
     for(int i=0;i<count;i++)
{
  //  tools.msgBox("hello");
  q= Integer.parseInt(tabcmd.getValueAt(i,5).toString())-Integer.parseInt(tabcmd.getValueAt(i,12).toString());
 //q=q-((Integer.parseInt(qtemed.getText())));
som= Float.parseFloat(tabcmd.getValueAt(i,6).toString());
stock=stock+(q*som);   
}    


String s=String.valueOf(stock);
s=s+"   DA";
mantant.setText(s);
med.requestFocus();
forn.setEnabled(false);
btnvalid.setEnabled(true);
btnadd.setEnabled(true);
btnsup.setEnabled(false);
}
       
        
        
        
        
    
    
    
   }         // TODO add your handling code here:
    }//GEN-LAST:event_ugKeyReleased

    private void qtemedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtemedKeyReleased
 if(evt.getKeyCode()==KeyEvent.VK_ENTER){

 nlot.requestFocus();

 }        // TODO add your handling code here:
    }//GEN-LAST:event_qtemedKeyReleased

    private void btnvalidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvalidActionPerformed
/*panevalid.setVisible(true);
a.getAllRows(tabcmd1);
        tabcmd1.getTableHeader().setBackground(new Color(0,0,100));
tabcmd1.getTableHeader().setForeground(Color.white);
tabcmd1.setShowGrid(false);
tabcmd1.setShowVerticalLines(false);
   tabcmd1.setColumnSelectionAllowed(false);
    tabcmd1.setRowSelectionAllowed(true);
    tabcmd1.setSelectionBackground(Color.red);
labnbf.setText(nbf.getText());
labtot.setText(mantant.getText());// TODO add your handling code here:*/
    }//GEN-LAST:event_btnvalidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        tools.openForm(new frmHome());
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
 public void resetColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(240,240,240));
 }
  public void resetColorv(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(45,118,232));
 }
  public void setColorv(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(255,0,0));
 }
  public void setColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(0,128,0));
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAchatretour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAchatretour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAchatretour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAchatretour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAchatretour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.ButtonGroup btngroup;
    private javax.swing.ButtonGroup btngroup2;
    private javax.swing.JButton btnsup;
    private javax.swing.JButton btnvalid;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser dateexp;
    private javax.swing.JTextField forn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mantant;
    private javax.swing.JTextField marge;
    private javax.swing.JTextField med;
    private javax.swing.JTextField nb;
    private javax.swing.JTextField nbf;
    private javax.swing.JTextField nlot;
    private javax.swing.JTextField para;
    private javax.swing.JTextField ppa;
    private javax.swing.JTextField prixVente;
    private javax.swing.JTextField prixmed;
    private javax.swing.JTextField prixpara;
    private javax.swing.JTextField qtemed;
    private javax.swing.JTextField qtepara;
    private javax.swing.JRadioButton rdobl;
    private javax.swing.JRadioButton rdof;
    private javax.swing.JTextField shp;
    private javax.swing.JScrollPane stabforn;
    private javax.swing.JScrollPane stabmed;
    private javax.swing.JScrollPane stabpara;
    private javax.swing.JTable tabcmd;
    private javax.swing.JTable tabforn;
    private javax.swing.JTable tabmed;
    private javax.swing.JTable tabpara;
    private javax.swing.JLabel txt;
    private javax.swing.JTextField ug;
    // End of variables declaration//GEN-END:variables
}
