/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import entity.achat;
import static forms.frmAchat.nbf;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import work.tools;

/**
 *
 * @author choqib
 */
public class frmAchatvalid extends javax.swing.JFrame {
 achat a = new achat();
    /**
     * Creates new form frmAchatvalid
     */
    public frmAchatvalid() {
     this.setUndecorated(false);
        this.setAlwaysOnTop(false);
       this.setResizable(false);
        this.setVisible(true);
        
    
        initComponents();
       
        this.setSize(1440, 750);
           tabcmd.getTableHeader().setBackground(new Color(0,0,100));
tabcmd.getTableHeader().setForeground(Color.white);
tabcmd.setShowGrid(false);
tabcmd.setShowVerticalLines(false);
   tabcmd.setColumnSelectionAllowed(false);
    tabcmd.setRowSelectionAllowed(true);
    tabcmd.setSelectionBackground(Color.white);
         a.getCustomRows("select nom_produit,n_lot,ppa,pht,pvent,qte,exp,shp,mge,ug from comande where nb_fact='"+
            nbf.getText()+"'", this.tabcmd);
        // tools.msgBox("nb=="+nbf.getText());
        total();
         
         

    }
public void total()
{
float stock=0,totshp=0,totppa=0,totsansremis=0,totremis=0;
int q,q1,count=tabcmd.getRowCount();float som,som1,som2,somsansremis,remis,remis1;
     for(int i=0;i<count;i++)
{
  q1=Integer.parseInt(tabcmd.getValueAt(i,5).toString());
  q= Integer.parseInt(tabcmd.getValueAt(i,5).toString())-Integer.parseInt(tabcmd.getValueAt(i,9).toString());
 //q=q-((Integer.parseInt(qtemed.getText())));
som= Float.parseFloat(tabcmd.getValueAt(i,3).toString());
stock=stock+(q*som); 
som1= Float.parseFloat(tabcmd.getValueAt(i,7).toString());
totshp=totshp+(q1*som1);
som2= Float.parseFloat(tabcmd.getValueAt(i,2).toString());
totppa=totppa+(q1*som2);
somsansremis=Float.parseFloat(tabcmd.getValueAt(i,3).toString());
totsansremis=totsansremis+(q1*somsansremis);
remis1=Float.parseFloat(tabcmd.getValueAt(i,3).toString());
remis=Float.parseFloat(tabcmd.getValueAt(i,9).toString());
totremis=totremis+(remis*remis1);
}
     total.setText(String.valueOf(stock)+" DA");
     totalshp.setText(String.valueOf(totshp)+" DA");
     totalppa.setText(String.valueOf(totppa)+" DA");
     totalsansremis.setText(String.valueOf(totsansremis)+" DA");
     this.remis.setText(String.valueOf(totremis)+" DA");
     
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nbr = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        nomfr = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabcmd = new javax.swing.JTable();
        total4 = new javax.swing.JLabel();
        totalppa = new javax.swing.JLabel();
        total14 = new javax.swing.JLabel();
        total16 = new javax.swing.JLabel();
        totalshp = new javax.swing.JLabel();
        total15 = new javax.swing.JLabel();
        remis = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        total5 = new javax.swing.JLabel();
        totalsansremis = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btvalidation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("N°                                  :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(71, 45, 200, 31);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Date d' Achat              :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(71, 82, 200, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Nom de Fournisseure:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(71, 119, 199, 31);

        nbr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(nbr);
        nbr.setBounds(277, 45, 370, 31);

        date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(date);
        date.setBounds(277, 82, 370, 31);

        nomfr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(nomfr);
        nomfr.setBounds(276, 119, 370, 31);

        tabcmd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabcmd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Désignation", "N° Lot", "PPA", "Prix Achat ", "Prix Vent", "QTE", "Date d'Exp", "Shp", "Marge", "UG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabcmd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabcmdMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabcmdMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabcmd);
        if (tabcmd.getColumnModel().getColumnCount() > 0) {
            tabcmd.getColumnModel().getColumn(0).setResizable(false);
            tabcmd.getColumnModel().getColumn(1).setResizable(false);
            tabcmd.getColumnModel().getColumn(2).setResizable(false);
            tabcmd.getColumnModel().getColumn(3).setResizable(false);
            tabcmd.getColumnModel().getColumn(4).setResizable(false);
            tabcmd.getColumnModel().getColumn(5).setResizable(false);
            tabcmd.getColumnModel().getColumn(6).setResizable(false);
            tabcmd.getColumnModel().getColumn(7).setResizable(false);
            tabcmd.getColumnModel().getColumn(8).setResizable(false);
            tabcmd.getColumnModel().getColumn(9).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 160, 1320, 240);

        total4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total4.setText("Total SHP            :");
        getContentPane().add(total4);
        total4.setBounds(680, 430, 130, 30);

        totalppa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(totalppa);
        totalppa.setBounds(810, 470, 230, 30);

        total14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total14.setText("Total  Net A Payer        :");
        getContentPane().add(total14);
        total14.setBounds(200, 510, 170, 32);

        total16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total16.setText("Remis                              :");
        getContentPane().add(total16);
        total16.setBounds(200, 470, 170, 32);

        totalshp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(totalshp);
        totalshp.setBounds(810, 430, 230, 30);

        total15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total15.setText("Total                               :");
        getContentPane().add(total15);
        total15.setBounds(200, 430, 170, 32);

        remis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(remis);
        remis.setBounds(370, 470, 320, 32);

        total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(total);
        total.setBounds(370, 510, 320, 32);

        total5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total5.setText("Total PPA             :");
        getContentPane().add(total5);
        total5.setBounds(680, 470, 130, 30);

        totalsansremis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(totalsansremis);
        totalsansremis.setBounds(370, 430, 320, 32);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 500, 1000, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 460, 1000, 15);

        btvalidation.setBackground(new java.awt.Color(0, 102, 0));
        btvalidation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btvalidation.setForeground(new java.awt.Color(255, 255, 255));
        btvalidation.setMnemonic('s');
        btvalidation.setText("Imprission");
        btvalidation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvalidationActionPerformed(evt);
            }
        });
        getContentPane().add(btvalidation);
        btvalidation.setBounds(1060, 30, 180, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabcmdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabcmdMouseClicked
      
        // TODO add your handling code here:
    }//GEN-LAST:event_tabcmdMouseClicked

    private void tabcmdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabcmdMouseReleased
        if(evt.isPopupTrigger()){
         
        }    // TODO add your handling code here:
    }//GEN-LAST:event_tabcmdMouseReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btvalidationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvalidationActionPerformed
    
        try {
            MessageFormat header = new MessageFormat("N°          :"+nbr.getText()+" \n"
                    + "Nom de fournisseur:"+nomfr.getText()+" \n"
                            + "Date      :"+date.getText()+" \n");
             MessageFormat footer = new MessageFormat(""
                     + "Total: "+totalsansremis.getText()+"                    Total SHP :"+totalshp.getText()+"  \n"
                     + "---------------------------------------------------------------------------------------------------\n"
                     + "Remise:"+remis.getText()+"                             Total PPA :"+totalppa.getText()+"  \n"
                     + "----------------------------------------------------------------------------------------------------\n"
                     +"Total  Net A Payer :"+total.getText()+"                 ---------------------------------------------\n"
                     + "\n Page -{0}-");
        
            tabcmd.print(JTable.PrintMode.FIT_WIDTH,header,footer);
            // TODO add your handling code here:
        } catch (PrinterException ex) {
            Logger.getLogger(frmMed.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btvalidationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAchatvalid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAchatvalid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAchatvalid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAchatvalid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAchatvalid().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btvalidation;
    public static javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel nbr;
    public static javax.swing.JLabel nomfr;
    private javax.swing.JLabel remis;
    public static javax.swing.JTable tabcmd;
    private javax.swing.JLabel total;
    private javax.swing.JLabel total14;
    private javax.swing.JLabel total15;
    private javax.swing.JLabel total16;
    private javax.swing.JLabel total4;
    private javax.swing.JLabel total5;
    private javax.swing.JLabel totalppa;
    private javax.swing.JLabel totalsansremis;
    private javax.swing.JLabel totalshp;
    // End of variables declaration//GEN-END:variables
}
