/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

//import com.sun.corba.se.impl.protocol.giopmsgheaders.Message;
import controls.mycolortable;
import entity.dci;
import entity.midicament;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.jdesktop.swingx.autocomplete.ObjectToStringConverter;
import work.tools;


/**
 *
 * @author choqib
 */
public class frmMed extends javax.swing.JFrame {
    midicament m = new midicament();
    dci d =new dci();
    private void data ()
    {
     tools.clearText(this);
    no.setText(m.getAutoNumber());
    btnadd.setEnabled(true);
    btndel.setEnabled(false);
    btnupd.setEnabled(false);

    nom.requestFocus();
    
    }
    /**
     * Creates new form frmMed
     */
    public frmMed() {
        this.setUndecorated(false);
        this.setAlwaysOnTop(false);
       this.setResizable(true);
        this.setVisible(true);
        
    int x1=3;
        initComponents();
        
         tabmed.setDefaultRenderer(Object.class, new mycolortable() );
          
      // jTable1.setDefaultRenderer(Object.class, new mycolortable() );
        Toolkit tk = Toolkit.getDefaultToolkit();
        int x=(int) tk.getScreenSize().getWidth();
        int y=(int) tk.getScreenSize().getHeight();
        this.setSize(950,670);
        m.getAllRows(tabmed);
        m.getAllRows1("produit", "forme", comboforme);
        AutoCompleteDecorator.decorate(comboforme);
        m.getAllRows1("dci", "nom_dci", dci);
        AutoCompleteDecorator.decorate(dci);
tabmed.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);        
        
       
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnadd = new controls.JMyButton();
        btnupd = new controls.JMyButton();
        btndel = new controls.JMyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabmed = new javax.swing.JTable();
        serch = new controls.JTextBox(25);
        printe = new controls.JMyButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboforme = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        dci = new javax.swing.JComboBox<>();
        nom = new javax.swing.JTextField();
        no = new javax.swing.JTextField();
        dosage = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(null);

        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/Actions-contact-new-icon.png"))); // NOI18N
        btnadd.setText("ajouter");
        btnadd.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd);
        btnadd.setBounds(110, 20, 120, 33);

        btnupd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/Actions-edit-redo-icon.png"))); // NOI18N
        btnupd.setText("M- A -J");
        btnupd.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnupd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdActionPerformed(evt);
            }
        });
        getContentPane().add(btnupd);
        btnupd.setBounds(240, 20, 120, 33);

        btndel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/Remove-event-icon.png"))); // NOI18N
        btndel.setText("supprimer");
        btndel.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });
        getContentPane().add(btndel);
        btndel.setBounds(370, 20, 120, 33);

        tabmed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tabmed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Désignation", "DCI", "Forme", "Dosage"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabmed.setGridColor(new java.awt.Color(255, 255, 255));
        tabmed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabmedMouseClicked(evt);
            }
        });
        tabmed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabmedKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabmedKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tabmedKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tabmed);
        if (tabmed.getColumnModel().getColumnCount() > 0) {
            tabmed.getColumnModel().getColumn(0).setResizable(false);
            tabmed.getColumnModel().getColumn(1).setResizable(false);
            tabmed.getColumnModel().getColumn(2).setResizable(false);
            tabmed.getColumnModel().getColumn(3).setResizable(false);
            tabmed.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 170, 880, 430);

        serch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        serch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serchKeyReleased(evt);
            }
        });
        getContentPane().add(serch);
        serch.setBounds(30, 120, 810, 40);

        printe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/Printer-icon.png"))); // NOI18N
        printe.setText("impression");
        printe.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        printe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printeActionPerformed(evt);
            }
        });
        getContentPane().add(printe);
        printe.setBounds(510, 20, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setText("Dosage");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(750, 50, 50, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setText("Désignation");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 50, 80, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setText("N°");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 50, 50, 30);

        comboforme.setEditable(true);
        comboforme.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(comboforme);
        comboforme.setBounds(610, 80, 130, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel21.setText("DCI");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(300, 50, 50, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel22.setText("Forme");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(610, 50, 50, 30);

        dci.setEditable(true);
        dci.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(dci);
        dci.setBounds(280, 80, 320, 30);

        nom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(nom);
        nom.setBounds(100, 80, 180, 30);

        no.setEditable(false);
        getContentPane().add(no);
        no.setBounds(30, 80, 59, 30);

        dosage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(dosage);
        dosage.setBounds(750, 80, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/ch33.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 80, 1370, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serchKeyReleased
tabmed.setVisible(true);

        m.getCustomRows("select id,nom,dci,forme,dosage from produit where nom LIKE'%"+serch.getText()+"%'", tabmed);
                
        
    }//GEN-LAST:event_serchKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
data(); 
tabmed.getTableHeader().setVisible(true);
tabmed.getTableHeader().setBackground(new Color(0,0,100));
tabmed.getTableHeader().setForeground(Color.white);
tabmed.setShowGrid(false);
tabmed.setShowVerticalLines(false);
   tabmed.setColumnSelectionAllowed(false);
    tabmed.setRowSelectionAllowed(true);
    tabmed.setSelectionBackground(Color.red);
tabmed.setRowSelectionInterval(0,0);
tabmed.setRowHeight(24);
btnadd.setEnabled(true);
btnupd.setEnabled(false);
btndel.setEnabled(false);
;// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
m.setIdm(Integer.parseInt(no.getText()));
m.setNom(nom.getText());
m.setDci((String)dci.getSelectedItem());
m.setForme((String)comboforme.getSelectedItem());
m.setDosage(dosage.getText());
m.add();    
m.getAllRows(tabmed);
data();
// TODO add your handling code here:
    }//GEN-LAST:event_btnaddActionPerformed

    private void tabmedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabmedMouseClicked
   int row =tabmed.getSelectedRow();
   String strno=tabmed.getValueAt(row, 0).toString();
   String strnom=tabmed.getValueAt(row, 1).toString();
   String strdci=tabmed.getValueAt(row, 2).toString();
   String strdos=tabmed.getValueAt(row, 4).toString();
   dosage.setText(strdos);
   no.setText(strno);
   nom.setText(strnom);
   dosage.setText(strdos);
   
   
   //dci1.setText(strdci);
   
  btnadd.setEnabled(false);
    btndel.setEnabled(true);
    btnupd.setEnabled(true);

// TODO add your handling code here:
    }//GEN-LAST:event_tabmedMouseClicked

    private void btnupdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdActionPerformed
m.setIdm(Integer.parseInt(no.getText()));
m.setNom(nom.getText());
m.setDci((String)dci.getSelectedItem());
m.setForme((String)comboforme.getSelectedItem());
m.setDosage(dosage.getText());
m.update();
m.getAllRows(tabmed);   
data();// TODO add your handling code here:
    }//GEN-LAST:event_btnupdActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
m.setIdm(Integer.parseInt(no.getText()));
m.setNom(nom.getText());
m.setDci((String)dci.getSelectedItem());
m.setForme((String)comboforme.getSelectedItem());
m.setDosage(dosage.getText());
m.delete();
m.getAllRows(tabmed);
data();// TODO add your handling code here:
    }//GEN-LAST:event_btndelActionPerformed

    private void printeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printeActionPerformed
        try {
            MessageFormat header = new MessageFormat("Listes des Medicaments");
             MessageFormat footer = new MessageFormat("Page -{0}-");
        
            tabmed.print(JTable.PrintMode.FIT_WIDTH,header,footer);
            // TODO add your handling code here:
        } catch (PrinterException ex) {
            Logger.getLogger(frmMed.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printeActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
btnadd.setEnabled(true);
btndel.setEnabled(false);
btnupd.setEnabled(false);
serch.setText("");
 m.getCustomRows("select id,nom,dci,forme,dosage from produit ", tabmed);
// TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void tabmedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabmedKeyPressed
 
        int row =tabmed.getSelectedRow();
        if((evt.getKeyCode()==KeyEvent.VK_DOWN) &(row<tabmed.getRowCount()))
{
 row++;
   String strno=tabmed.getValueAt(row, 0).toString();
   String strnom=tabmed.getValueAt(row, 1).toString();
   String strdci=tabmed.getValueAt(row, 2).toString();
   String strdos=tabmed.getValueAt(row, 4).toString();
   dosage.setText(strdos);
   no.setText(strno);
   nom.setText(strnom);
   
  
}
      if((evt.getKeyCode()==KeyEvent.VK_UP)& (row>=0)& (tabmed.getRowCount()>=row))
{
row =row-1;
   String strno=tabmed.getValueAt(row, 0).toString();
   String strnom=tabmed.getValueAt(row, 1).toString();
   String strdci=tabmed.getValueAt(row, 2).toString();
   String strdos=tabmed.getValueAt(row, 4).toString();
   dosage.setText(strdos);
   no.setText(strno);
   nom.setText(strnom);

}
       
   //dci1.setText(strdci);
   
  btnadd.setEnabled(false);
    btndel.setEnabled(true);
    btnupd.setEnabled(true);
      // TODO add your handling code here:
    }//GEN-LAST:event_tabmedKeyPressed

    private void tabmedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabmedKeyTyped
   
    int row =tabmed.getSelectedRow();
    
   String strno=tabmed.getValueAt(row, 0).toString();
   String strnom=tabmed.getValueAt(row, 1).toString();
   String strdci=tabmed.getValueAt(row, 2).toString();
   String strdos=tabmed.getValueAt(row, 4).toString();
   dosage.setText(strdos);
   no.setText(strno);
   nom.setText(strnom);

   //dci1.setText(strdci);
   
  btnadd.setEnabled(false);
    btndel.setEnabled(true);
    btnupd.setEnabled(true);
 // TODO add your handling code here:
    }//GEN-LAST:event_tabmedKeyTyped

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        int x=3;
       
        if((evt.getKeyCode()==KeyEvent.VK_DOWN) &(x>=0)&(x<=5))
{
    x--;
tabmed.setRowSelectionInterval(x,x);

}      // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped
int selectedRow=1;
    private void tabmedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabmedKeyReleased
    String keyChar = String.valueOf(evt.getKeyChar());
        TableModel model = tabmed.getModel();
        int startRow = selectedRow;
        if (selectedRow == model.getRowCount() - 1) {
            startRow = -1;//Go before start
        }
        //Check each cell to see if it starts with typed char.
        //if so set corresponding row selected and return.
        for (int row = startRow+1; row < model.getRowCount(); row++) {
            for (int col = 0; col < model.getColumnCount(); col++) {
                String value = (String) model.getValueAt(row, col);
                if (value != null && value.startsWith(keyChar)) {
                    tabmed.getSelectionModel().clearSelection();
                    tabmed.getColumnModel().getSelectionModel().clearSelection();
                    tabmed.setRowSelectionInterval(row, row);
                    selectedRow = row;
                    return;
                }
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tabmedKeyReleased

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
           String keyChar = String.valueOf(evt.getKeyChar());
        TableModel model = tabmed.getModel();
        int startRow = selectedRow;
        if (selectedRow == model.getRowCount() - 1) {
            startRow = -1;//Go before start
        }
        //Check each cell to see if it starts with typed char.
        //if so set corresponding row selected and return.
        for (int row = startRow+1; row < model.getRowCount(); row++) {
            for (int col = 0; col < model.getColumnCount(); col++) {
                String value = (String) model.getValueAt(row, col);
                if (value != null && value.startsWith(keyChar)) {
                    tabmed.getSelectionModel().clearSelection();
                    tabmed.getColumnModel().getSelectionModel().clearSelection();
                    tabmed.setRowSelectionInterval(row, row);
                    selectedRow = row;
                    return;
                }
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased
int x=0;
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
  
       
        if((evt.getKeyCode()==KeyEvent.VK_DOWN) &(x>=0)&(x<=5))
{
    if((x>=0)&(x<=5)){}
    x=x-1;
tabmed.setRowSelectionInterval(x,x);

}           // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed
 public void resetColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(240,240,240));
 }
  public void resetColorv(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(45,118,232));
 }
  public void setColorv(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(255,0,0));
 }
  public void setColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(0,128,0));
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyButton btnadd;
    private controls.JMyButton btndel;
    private controls.JMyButton btnupd;
    private javax.swing.JComboBox<String> comboforme;
    private javax.swing.JComboBox<String> dci;
    private javax.swing.JTextField dosage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField no;
    private javax.swing.JTextField nom;
    private controls.JMyButton printe;
    private javax.swing.JTextField serch;
    private javax.swing.JTable tabmed;
    // End of variables declaration//GEN-END:variables
}
