/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import entity.midicament;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import work.tools;

/**
 *
 * @author choqib
 */
public class frmMain extends javax.swing.JFrame {
midicament m=new midicament();
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
      //   m.getAllRows(tab_mid);
    }
 private void formWindowOpened(java.awt.event.WindowEvent evt) { 
    
        
        //proj.getAllRows(tblProject);
        
        
        
        
      //  tblProject.getTableHeader().setReorderingAllowed(false);
    }
 //midicament proj = new midicament();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMyButton1 = new controls.JMyButton();
        jMyButton2 = new controls.JMyButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1350, 750));
        getContentPane().setLayout(null);

        jMyButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/medical-case-icon.png"))); // NOI18N
        jMyButton1.setText("Medicament");
        jMyButton1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        getContentPane().add(jMyButton1);
        jMyButton1.setBounds(320, 10, 140, 33);

        jMyButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/prescription-icon2.png"))); // NOI18N
        jMyButton2.setText("Ordonance");
        jMyButton2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        getContentPane().add(jMyButton2);
        jMyButton2.setBounds(170, 10, 130, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/ch_pharm1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 1360, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
             
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private controls.JMyButton jMyButton1;
    private controls.JMyButton jMyButton2;
    // End of variables declaration//GEN-END:variables
}
