/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import controls.mycolortable;
import entity.client;
import entity.ordonance;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumn;
import work.tools;

/**
 *
 * @author choqib
 */
public class frmretour extends javax.swing.JFrame {
    
    client c= new client();
    ordonance o=new ordonance();
     Date d=new Date();
        SimpleDateFormat a = new SimpleDateFormat("yyyy-MM-dd");
    public frmretour() {
        
         this.setUndecorated(false);
        this.setAlwaysOnTop(false);
       this.setResizable(false);
        this.setVisible(true);
        
    
        initComponents();
 //tabmed.setDefaultRenderer(Object.class, new mycolortable() ); 
       combo.setDefaultRenderer(Object.class, new mycolortable() );
       combo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.setSize(781, 430);
        cc.setVisible(false);
    lenom.setVisible(false);
   jTable1.setVisible(false);
   jScrollPane1.setVisible(false);
        pan.setVisible(false);
        combo.setVisible(false);
         combo.getTableHeader().setBackground(new Color(0,0,100));
combo.getTableHeader().setForeground(Color.white);
combo.setShowGrid(false);
combo.setShowVerticalLines(false);
   combo.setColumnSelectionAllowed(false);
    combo.setRowSelectionAllowed(true);
    combo.setSelectionBackground(Color.green);  
    combo.setRowHeight(24);
    combo.setRowHeight(24);
    combo.setAutoResizeMode(combo.AUTO_RESIZE_OFF);
 TableColumn col=combo.getColumnModel().getColumn(0);
 col.setPreferredWidth(40);
 col=combo.getColumnModel().getColumn(1);
 col.setPreferredWidth(320);
  col=combo.getColumnModel().getColumn(2);
 col.setPreferredWidth(70);
  col=combo.getColumnModel().getColumn(3);
 col.setPreferredWidth(60);
  col=combo.getColumnModel().getColumn(4);
 col.setPreferredWidth(40);
   col=combo.getColumnModel().getColumn(5);
 col.setPreferredWidth(75);
  col=combo.getColumnModel().getColumn(6);
 col.setPreferredWidth(75);
 jLabel3.setVisible(false);
  ins.setVisible(false);
 
        
    }
String p,q,nm,l,dateexp;int nbr;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        radj = new javax.swing.JRadioButton();
        radautr = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        prix = new javax.swing.JTextField();
        annuler = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pan = new javax.swing.JScrollPane();
        combo = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        qte = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        valid = new javax.swing.JButton();
        ins = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cc = new javax.swing.JLabel();
        lenom = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Je vendu le Produit");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 20, 119, 20);

        radj.setBackground(new java.awt.Color(255, 255, 255));
        radj.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radj.setMnemonic('a');
        radj.setSelected(true);
        radj.setText("Aujour d'hui");
        radj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radjActionPerformed(evt);
            }
        });
        getContentPane().add(radj);
        radj.setBounds(240, 20, 101, 20);

        radautr.setBackground(new java.awt.Color(255, 255, 255));
        radautr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radautr.setMnemonic('u');
        radautr.setText("Auparavant");
        radautr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radautrActionPerformed(evt);
            }
        });
        getContentPane().add(radautr);
        radautr.setBounds(380, 20, 97, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Le Prix (DA)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 70, 78, 15);

        prix.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prixKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prixKeyTyped(evt);
            }
        });
        getContentPane().add(prix);
        prix.setBounds(250, 60, 168, 30);

        annuler.setBackground(new java.awt.Color(255, 0, 0));
        annuler.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        annuler.setForeground(new java.awt.Color(255, 255, 255));
        annuler.setMnemonic('n');
        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });
        getContentPane().add(annuler);
        annuler.setBounds(320, 310, 180, 30);

        jLabel3.setText("Aucune Produit trouver");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 290, 186, 14);

        combo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° Ord", "Désignation", "N° Lot", "Prix", "Qte", "Date de Vente", "Date EXP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        combo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                comboKeyReleased(evt);
            }
        });
        pan.setViewportView(combo);
        if (combo.getColumnModel().getColumnCount() > 0) {
            combo.getColumnModel().getColumn(0).setResizable(false);
            combo.getColumnModel().getColumn(1).setResizable(false);
            combo.getColumnModel().getColumn(2).setResizable(false);
            combo.getColumnModel().getColumn(3).setResizable(false);
            combo.getColumnModel().getColumn(4).setResizable(false);
            combo.getColumnModel().getColumn(5).setResizable(false);
            combo.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(pan);
        pan.setBounds(10, 150, 720, 130);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Quantité");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 210, 78, 15);

        qte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qteKeyTyped(evt);
            }
        });
        getContentPane().add(qte);
        qte.setBounds(150, 200, 168, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Total");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(390, 210, 40, 17);

        total.setEditable(false);
        total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(total);
        total.setBounds(440, 200, 137, 30);

        nom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        getContentPane().add(nom);
        nom.setBounds(10, 110, 720, 40);

        valid.setBackground(new java.awt.Color(0, 102, 0));
        valid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        valid.setForeground(new java.awt.Color(255, 255, 255));
        valid.setMnemonic('v');
        valid.setText("Valider");
        valid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validActionPerformed(evt);
            }
        });
        getContentPane().add(valid);
        valid.setBounds(70, 310, 180, 30);

        ins.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ins.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ins);
        ins.setBounds(110, 160, 220, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/retour.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 0, 130, 120);

        cc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cc.setText("nom de client");
        getContentPane().add(cc);
        cc.setBounds(630, 280, 110, 30);

        lenom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(lenom);
        lenom.setBounds(620, 310, 140, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("___________________");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(620, 290, 160, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("___________________");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(620, 330, 160, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/re.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 640, 420);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(660, 30, 110, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radjActionPerformed
tools.clearText(this);        // TODO add your handling code here:
    }//GEN-LAST:event_radjActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
btngroup1.add(radj);
 btngroup1.add(radautr); 
 prix.requestFocus();
 // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void prixKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prixKeyReleased
   jLabel3.setVisible(true);
        if(prix.getText().isEmpty()){pan.setVisible(false);
        combo.setVisible(false);}
    else{
        pan.setVisible(true);
        combo.setVisible(true);
        if(radj.isSelected()){
        //o.getAllRows1("ordonanace where prix="+Float.parseFloat(prix.getText())+"AND date='"+a.format(d)+"'", "nom_produit", combo);
        o.getCustomRows("select id_ord,nom_produit ,n_lot,prix,qte,date,date_exp from ordonanace where prix="+
                Float.parseFloat(prix.getText())+"AND date='"+a.format(d)+"' AND qte>0", combo);
        
      int i=combo.getRowCount();
     //o.getValueByName1("");
              jLabel3.setText(i+" Produits trouver");
          if(i==0){jLabel3.setText("aucun Produit trouver");pan.setVisible(false);
        combo.setVisible(false);}    
     }
      if(radautr.isSelected()){
o.getCustomRows("select id_ord,nom_produit ,n_lot,prix,qte,date,date_exp from ordonanace where prix="+
                Float.parseFloat(prix.getText()) +"AND date<'"+a.format(d)+"' AND qte>0 AND (type='cash' OR type='credit client')", combo);

       // o.getAllRows1("ordonanace where prix="+Float.parseFloat(prix.getText()), "nom_produit", combo);
     int i=combo.getRowCount();
    // o.getValueByName1("");
              jLabel3.setText(i+"  Produits trouver");
              if(i==0){jLabel3.setText("aucun Produit trouver");pan.setVisible(false);
        combo.setVisible(false);}  
     }
     if(evt.getKeyCode()==KeyEvent.VK_ENTER){
       if(combo.getRowCount()==1){
       int row=combo.getSelectedRow();
 nbr=Integer.parseInt(combo.getValueAt(0, 0).toString());
 nm=combo.getValueAt(0, 1).toString();
 q=combo.getValueAt(0, 4).toString();
 p=combo.getValueAt(0, 3).toString();
 l=combo.getValueAt(0, 2).toString();
 dateexp=combo.getValueAt(0, 6).toString();
 String id=(o.getByName(nm,nbr,Float.parseFloat(p)));
 //tools.msgBox(id);
o.getCustomRows("select nom_client from ordonanace where id_ord="+Integer.parseInt(id)+" AND type='credit client'", jTable1); 
if(jTable1.getRowCount()>0){
    cc.setVisible(true);
    lenom.setVisible(true);
    lenom.setText(jTable1.getValueAt(0,0).toString());
    
}
float p1=Float.parseFloat(p);
int q1=Integer.parseInt(q);
total.setText(String.valueOf(q1*p1));
//total.setText(String.valueOf)(Float.parseFloat(p)*Integer.parseInt(q));
nom.setText(nm);
qte.setText(q);
pan.setVisible(false);
combo.setVisible(false);
 qte.requestFocus();
 qte.selectAll();
       }
       else{
           combo.requestFocus();
       }
     }
    }
// TODO add your handling code here:
    }//GEN-LAST:event_prixKeyReleased

    private void qteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qteKeyReleased

        float p1=Float.parseFloat(p);
     int q1=Integer.parseInt(q);
if(Integer.parseInt(qte.getText())<=q1){
total.setText(String.valueOf(Integer.parseInt(qte.getText())*p1));

} 
else{
ins.setVisible(true);
 ins.setText("la quantités insufuser de "+q1);
//tools.msgBox("le quantités insufuser de "+q1);
    qte.setText(String.valueOf(q1));
    qte.selectAll();
}
     if(evt.getKeyCode()==KeyEvent.VK_ENTER){
          if((prix.getText().isEmpty())|(nom.getText().isEmpty())|(qte.getText().isEmpty())){
        tools.msgBox("selectioner votre retour");
        prix.requestFocus();
        }
        else{
        
            if(tools.confirmMsg("Êtes-vous sûr de retour?")){
        String exp=dateexp;   
       float price =Float.parseFloat(p);
        String l1=l;
        String nm1=nm;
       // String idclient=c.getValueByName(lenom.getText());
       // String oldtotal=c.gettotalbyid(idclient);
        //c.updateClient(Float.parseFloat(oldtotal),Float.parseFloat(total.getText()));
        String id=String.valueOf(nbr);
        
        String idd=(o.getqteByName(nm1,l1,price,exp));
        int qtt=Integer.parseInt(o.getqte(id));
       // int qttcmd=Integer.parseInt(o.getqtecmd(idd));
        float tot=Float.parseFloat(o.getprixtotal(id));
        o.updateordonance(Integer.parseInt(qte.getText()),qtt, Float.parseFloat(total.getText()), tot,Integer.parseInt(id));
    
        o.updatecmd(Integer.parseInt(qte.getText()),Integer.parseInt(idd),l1,exp,price,nm1);
        
        nom.setText("");
        prix.setText("");
        qte.setText("");
        total.setText("");
        
        prix.requestFocus();
                }
            else{
            prix.requestFocus();
            }
        }
  
     }
// TODO add your handling code here:
    }//GEN-LAST:event_qteKeyReleased

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void comboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboKeyReleased
if(evt.getKeyCode()==KeyEvent.VK_ENTER){

            int row=combo.getSelectedRow();
            int rowc=combo.getRowCount();
            if(row==0){
                nbr=Integer.parseInt(combo.getValueAt(rowc-1, 0).toString());
                 nm=combo.getValueAt(rowc-1, 1).toString();
             q=combo.getValueAt(rowc-1, 4).toString();  
             p=combo.getValueAt(rowc-1, 3).toString();
              l=combo.getValueAt(rowc-1, 2).toString();
              dateexp=combo.getValueAt(rowc-1, 6).toString();
              String id=String.valueOf(nbr);
              o.getCustomRows("select nom_client from ordonanace where id_ord="+Integer.parseInt(id)+" AND type='credit client'", jTable1); 
if(jTable1.getRowCount()>0){
    cc.setVisible(true);
    lenom.setVisible(true);
    lenom.setText(jTable1.getValueAt(0,0).toString());
    
}
float p1=Float.parseFloat(p);
int q1=Integer.parseInt(q);
total.setText(String.valueOf(q1*p1));
            nom.setText(nm);
           qte.setText(q);
           pan.setVisible(false);
         combo.setVisible(false);
         qte.requestFocus();
 qte.selectAll();
            }
            else{
                  nbr=Integer.parseInt(combo.getValueAt(row-1, 0).toString());
                     nm=combo.getValueAt(row-1, 1).toString();
            q=combo.getValueAt(row-1, 4).toString(); 
             p=combo.getValueAt(row-1, 3).toString();
              l=combo.getValueAt(row-1, 2).toString();
             dateexp=combo.getValueAt(row-1, 6).toString();
                 String id=String.valueOf(nbr);
              o.getCustomRows("select nom_client from ordonanace where id_ord="+Integer.parseInt(id)+" AND type='credit client'", jTable1); 
if(jTable1.getRowCount()>0){
    cc.setVisible(true);
    lenom.setVisible(true);
    lenom.setText(jTable1.getValueAt(0,0).toString());
    
}
float p1=Float.parseFloat(p);
int q1=Integer.parseInt(q);
total.setText(String.valueOf(q1*p1));
            nom.setText(nm);
           qte.setText(q);
           pan.setVisible(false);
         combo.setVisible(false);
         qte.requestFocus();
 qte.selectAll();
            
            }
}// TODO add your handling code here:
    }//GEN-LAST:event_comboKeyReleased

    private void validActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validActionPerformed
        if((prix.getText().isEmpty())|(nom.getText().isEmpty())|(qte.getText().isEmpty())){
        tools.msgBox("selectioner votre retour");
        prix.requestFocus();
        }
        else{
        
            if(tools.confirmMsg("Êtes-vous sûr de retour?")){
        String exp=dateexp;   
       float price =Float.parseFloat(p);
        String l1=l;
        String nm1=nm;
       // String idclient=c.getValueByName(lenom.getText());
       // String oldtotal=c.gettotalbyid(idclient);
        //c.updateClient(Float.parseFloat(oldtotal),Float.parseFloat(total.getText()));
      String id=String.valueOf(nbr);
        
        String idd=(o.getqteByName(nm1,l1,price,exp));
        int qtt=Integer.parseInt(o.getqte(id));
       // int qttcmd=Integer.parseInt(o.getqtecmd(idd));
        float tot=Float.parseFloat(o.getprixtotal(id));
        o.updateordonance(Integer.parseInt(qte.getText()),qtt, Float.parseFloat(total.getText()), tot,Integer.parseInt(id));
    
        o.updatecmd(Integer.parseInt(qte.getText()),Integer.parseInt(idd),l1,exp,price,nm1);
        
        nom.setText("");
        prix.setText("");
        qte.setText("");
        total.setText("");
        
        prix.requestFocus();
                }
            else{
            prix.requestFocus();
            }
        }
    }//GEN-LAST:event_validActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed

        tools.openForm(new frmVente());
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_annulerActionPerformed

    private void radautrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radautrActionPerformed
tools.clearText(this);               // TODO add your handling code here:
    }//GEN-LAST:event_radautrActionPerformed

    private void qteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qteKeyTyped
char c=evt.getKeyChar();
if(!((Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)||(c==KeyEvent.VK_ENTER))){
    getToolkit().beep();
    evt.consume();


}         // TODO add your handling code here:
    }//GEN-LAST:event_qteKeyTyped

    private void prixKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prixKeyTyped
char c=evt.getKeyChar();
if(!((Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)||(c==KeyEvent.VK_PERIOD)||(c==KeyEvent.VK_ENTER))){
    getToolkit().beep();
    evt.consume();


}      // TODO add your handling code here:
           // TODO add your handling code here:
    }//GEN-LAST:event_prixKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmretour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmretour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmretour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmretour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmretour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.ButtonGroup btngroup1;
    private javax.swing.JLabel cc;
    private javax.swing.JTable combo;
    private javax.swing.JLabel ins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lenom;
    private javax.swing.JTextField nom;
    private javax.swing.JScrollPane pan;
    private javax.swing.JTextField prix;
    private javax.swing.JTextField qte;
    private javax.swing.JRadioButton radautr;
    private javax.swing.JRadioButton radj;
    private javax.swing.JTextField total;
    private javax.swing.JButton valid;
    // End of variables declaration//GEN-END:variables
}
