/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import entity.ordonance;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author choqib
 */
public class frmrecette extends javax.swing.JFrame {

    /**
     * Creates new form frmrecette
     */
    public frmrecette() {
              
 this.setUndecorated(false);
        this.setAlwaysOnTop(false);
       this.setResizable(false);
        this.setVisible(true);
        
    
        initComponents();
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        int x=(int) tk.getScreenSize().getWidth();
        int y=(int) tk.getScreenSize().getHeight();
        this.setSize(632, 620);
        jScrollPane1.setVisible(false);
        jTable1.setVisible(false);
        jScrollPane2.setVisible(false);
        jTable2.setVisible(false);
        jScrollPane3.setVisible(false);
        jTable3.setVisible(false);
        jScrollPane4.setVisible(false);
        jTable4.setVisible(false);
        
        Calendar clndr =Calendar.getInstance();
 datedebut.setCalendar(clndr);
 datefin.setCalendar(clndr);
  SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
  
       String HDate1 = String.valueOf(f.format( datedebut.getDate() ));
       String HDate2 = String.valueOf(f.format( datefin.getDate() ));
        ordonance o= new ordonance();
        o.getCustomRows("select qte,total from ordonanace where date between '"+HDate1+"' AND '"+HDate2+"'", jTable1);
        int count=jTable1.getRowCount(),qtt=0;
        float som=0;
      
        for(int i =0;i<count;i++)
        {
        qtt=qtt+Integer.parseInt(jTable1.getValueAt(i,0).toString());
        som=som+Float.parseFloat(jTable1.getValueAt(i,1).toString());
        }
 nbrtotVent.setText(String.valueOf(qtt));
 recettetot.setText(String.valueOf(som));
 //recetteesp.setText(String.valueOf(som));
      o.getCustomRows("select qte,total from ordonanace where type='cash' AND (date between '"+HDate1+"' AND '"+HDate2+"')", jTable2);
         int count1=jTable2.getRowCount();
         qtt=0;
         som=0;
      
        for(int i =0;i<count1;i++)
        {
        qtt=qtt+Integer.parseInt(jTable2.getValueAt(i,0).toString());
        som=som+Float.parseFloat(jTable2.getValueAt(i,1).toString());
        }
 nbrtotCash.setText(String.valueOf(qtt));
 somcash.setText(String.valueOf(som));
 recetteesp.setText(String.valueOf(som));
        o.getCustomRows("select qte,total from ordonanace where type='credit client' AND ( date between '"+HDate1+"' AND '"+HDate2+"')", jTable3);
         int count2=jTable3.getRowCount();
         qtt=0;
         som=0;
      
        for(int i =0;i<count2;i++)
        {
        qtt=qtt+Integer.parseInt(jTable3.getValueAt(i,0).toString());
        som=som+Float.parseFloat(jTable3.getValueAt(i,1).toString());
        }
 nbrtotcredit.setText(String.valueOf(qtt));
 somcredit.setText(String.valueOf(som));
         o.getCustomRows("select qte,total from ordonanace where type='chifa' AND (date between '"+HDate1+"' AND '"+HDate2+"')", jTable4);
         int count3=jTable4.getRowCount();
         qtt=0;
         som=0;
      
        for(int i =0;i<count3;i++)
        {
        qtt=qtt+Integer.parseInt(jTable4.getValueAt(i,0).toString());
        som=som+Float.parseFloat(jTable4.getValueAt(i,1).toString());
        }
 nbrtotalchifa.setText(String.valueOf(qtt));
 somchifa.setText(String.valueOf(som));
 //recetteesp.setText(String.valueOf(som));
 
    }
void cash()
{


}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datedebut = new com.toedter.calendar.JDateChooser();
        datefin = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btvalidation = new javax.swing.JButton();
        nbrtotVent = new javax.swing.JTextField();
        nbrtotCash = new javax.swing.JTextField();
        nbrtotalchifa = new javax.swing.JTextField();
        nbrtotcredit = new javax.swing.JTextField();
        somcash = new javax.swing.JTextField();
        somchifa = new javax.swing.JTextField();
        somcredit = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        recettetot = new javax.swing.JTextField();
        recetteesp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        datedebut.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(datedebut);
        datedebut.setBounds(40, 20, 130, 30);

        datefin.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(datefin);
        datefin.setBounds(200, 20, 130, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Du:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 21, 21, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Au:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(174, 21, 21, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("-----------------------------------------------------------------------------------------------------------------------------");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 62, 625, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nombre total des Ventes            :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 109, 205, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nombre des Ventes cash             :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 146, 205, 26);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nombre des Ventes Cnas/CasNos:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 181, 205, 26);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nombre des Ventes Crédit Client:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 221, 205, 26);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("-----------------------------------------------------------------------------------------------------------------------------");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 254, 625, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Total cash                          :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(180, 290, 173, 29);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Total Cnas/casnos              :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(180, 326, 173, 29);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Total Crédit Client              :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(180, 362, 173, 29);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Payment des Crédits Client :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(180, 398, 173, 29);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("-----------------------------------------------------------------------------------------------------------------------------");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 438, 625, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Recette Espace  :");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(235, 462, 113, 29);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("-----------------------------------------------------------------------------------------------------------------------------");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 497, 625, 17);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Solde caisse      :    ");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(237, 533, 117, 29);

        btvalidation.setBackground(new java.awt.Color(0, 102, 0));
        btvalidation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btvalidation.setForeground(new java.awt.Color(255, 255, 255));
        btvalidation.setMnemonic('s');
        btvalidation.setText("Actualiser");
        btvalidation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvalidationActionPerformed(evt);
            }
        });
        getContentPane().add(btvalidation);
        btvalidation.setBounds(450, 20, 150, 30);

        nbrtotVent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nbrtotVent.setEnabled(false);
        getContentPane().add(nbrtotVent);
        nbrtotVent.setBounds(219, 108, 258, 29);

        nbrtotCash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nbrtotCash.setEnabled(false);
        getContentPane().add(nbrtotCash);
        nbrtotCash.setBounds(219, 144, 258, 29);

        nbrtotalchifa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nbrtotalchifa.setEnabled(false);
        getContentPane().add(nbrtotalchifa);
        nbrtotalchifa.setBounds(219, 179, 258, 29);

        nbrtotcredit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nbrtotcredit.setEnabled(false);
        getContentPane().add(nbrtotcredit);
        nbrtotcredit.setBounds(219, 219, 258, 29);

        somcash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        somcash.setEnabled(false);
        getContentPane().add(somcash);
        somcash.setBounds(357, 289, 258, 29);

        somchifa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        somchifa.setEnabled(false);
        getContentPane().add(somchifa);
        somchifa.setBounds(357, 325, 258, 29);

        somcredit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        somcredit.setEnabled(false);
        getContentPane().add(somcredit);
        somcredit.setBounds(357, 361, 258, 29);

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField8.setEnabled(false);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(357, 397, 258, 29);

        recettetot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recettetot.setForeground(new java.awt.Color(204, 0, 0));
        recettetot.setEnabled(false);
        getContentPane().add(recettetot);
        recettetot.setBounds(358, 532, 258, 29);

        recetteesp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recetteesp.setForeground(new java.awt.Color(0, 102, 0));
        recetteesp.setEnabled(false);
        getContentPane().add(recetteesp);
        recetteesp.setBounds(357, 461, 258, 29);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 560, 60, 50);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 510, 60, 50);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
            jTable3.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(80, 510, 60, 50);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(0).setResizable(false);
            jTable4.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(10, 560, 60, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btvalidationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvalidationActionPerformed

  SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
  
       String HDate1 = String.valueOf(f.format( datedebut.getDate() ));
       String HDate2 = String.valueOf(f.format( datefin.getDate() ));
        ordonance o= new ordonance();
        o.getCustomRows("select qte,total from ordonanace where date between '"+HDate1+"' AND '"+HDate2+"'", jTable1);
        int count=jTable1.getRowCount(),qtt=0;
        float som=0;
      
        for(int i =0;i<count;i++)
        {
        qtt=qtt+Integer.parseInt(jTable1.getValueAt(i,0).toString());
        som=som+Float.parseFloat(jTable1.getValueAt(i,1).toString());
        }
 nbrtotVent.setText(String.valueOf(qtt));

 recettetot.setText(String.valueOf(som));
       o.getCustomRows("select qte,total from ordonanace where type='cash' AND ( date between '"+HDate1+"' AND '"+HDate2+"')", jTable2);
         int count1=jTable2.getRowCount();
         qtt=0;
         som=0;
      
        for(int i =0;i<count1;i++)
        {
        qtt=qtt+Integer.parseInt(jTable2.getValueAt(i,0).toString());
        som=som+Float.parseFloat(jTable2.getValueAt(i,1).toString());
        }
 nbrtotCash.setText(String.valueOf(qtt));
 somcash.setText(String.valueOf(som));
 recetteesp.setText(String.valueOf(som));
        o.getCustomRows("select qte,total from ordonanace where type='credit client' AND (date between '"+HDate1+"' AND '"+HDate2+"')", jTable3);
         int count2=jTable3.getRowCount();
         qtt=0;
         som=0;
      
        for(int i =0;i<count2;i++)
        {
        qtt=qtt+Integer.parseInt(jTable3.getValueAt(i,0).toString());
        som=som+Float.parseFloat(jTable3.getValueAt(i,1).toString());
        }
 nbrtotcredit.setText(String.valueOf(qtt));
 somcredit.setText(String.valueOf(som));
         o.getCustomRows("select qte,total from ordonanace where type='chifa' AND (date between '"+HDate1+"' AND '"+HDate2+"')", jTable4);
         int count3=jTable4.getRowCount();
         qtt=0;
         som=0;
      
        for(int i =0;i<count3;i++)
        {
        qtt=qtt+Integer.parseInt(jTable4.getValueAt(i,0).toString());
        som=som+Float.parseFloat(jTable4.getValueAt(i,1).toString());
        }
 nbrtotalchifa.setText(String.valueOf(qtt));
 somchifa.setText(String.valueOf(som));
 //recetteesp.setText(String.valueOf(som)

        // TODO add your handling code here:
    }//GEN-LAST:event_btvalidationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmrecette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmrecette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmrecette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmrecette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmrecette().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btvalidation;
    private com.toedter.calendar.JDateChooser datedebut;
    private com.toedter.calendar.JDateChooser datefin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField nbrtotCash;
    private javax.swing.JTextField nbrtotVent;
    private javax.swing.JTextField nbrtotalchifa;
    private javax.swing.JTextField nbrtotcredit;
    private javax.swing.JTextField recetteesp;
    private javax.swing.JTextField recettetot;
    private javax.swing.JTextField somcash;
    private javax.swing.JTextField somchifa;
    private javax.swing.JTextField somcredit;
    // End of variables declaration//GEN-END:variables
}
