/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import controls.mycolortable;
import entity.midicament;
import entity.ordonance;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.Timer;
import javax.swing.table.TableColumn;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import work.tools;

/**
 *
 * @author choqib
 */
public class frmVente extends javax.swing.JFrame {
midicament m=new midicament();
 ordonance o=new ordonance();
 float prim;
 String d,qtt;
 String nlot1,nom;String HDate1;
 int qtestock,q,id,id_stock;
    /**
     * Creates new form frmVente
     */void showtime(){
     new Timer(0, new ActionListener(){
         @Override
         public void actionPerformed(ActionEvent e) {
              Calendar clndr =Calendar.getInstance();
                clndr.add(Calendar.DATE,+180);
         SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        date1.setCalendar(clndr);
      HDate1 = String.valueOf(f.format( date1.getDate() ));
Date d=new Date();
        SimpleDateFormat a = new SimpleDateFormat("yyyy-MM-dd");
         time.setText(a.format(d)); 
        SimpleDateFormat a2 = new SimpleDateFormat("hh:mm:ss");
        time1.setText(a2.format(d));
         }
    
     
     }).start();
     
     }
    public frmVente() {
 this.setUndecorated(false);
        this.setAlwaysOnTop(false);
       this.setResizable(false);
        this.setVisible(true);
        
    
        initComponents();
       tabmed.setDefaultRenderer(Object.class, new mycolortable() ); 
       jTable1.setDefaultRenderer(Object.class, new mycolortable() );
       tabmed.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        Toolkit tk = Toolkit.getDefaultToolkit();
        int x=(int) tk.getScreenSize().getWidth();
        int y=(int) tk.getScreenSize().getHeight();
        this.setSize(1440, 750);
        jTable3.setVisible(false);
        jScrollPane3.setVisible(false);
        date1.setVisible(false);
         btngroupmoney.add(oui);
         btngroupmoney.add(non);
        jTable1.setVisible(false);
        jScrollPane2.setVisible(false);
        nameprodect.setVisible(false);
        nlotactive.setVisible(false);
        nlotproduit.setVisible(false);
        expdate1.setVisible(false);
        expdate.setVisible(false);
        expdate2.setVisible(false);
        tableuprix.setVisible(false);


        prix.requestFocus();
        panelcaisse.setVisible(false);
       Calendar clndr =Calendar.getInstance();
       d=String.valueOf(clndr.get(Calendar.YEAR))+"-"+String.valueOf(clndr.get(Calendar.MONTH))+"-"+
             String.valueOf(clndr.get(Calendar.DATE));
       showtime();
    
          
       nbordonance.setText(db.go.getAutoNumber("ordonanace", "nbr"));
           tabmed.getTableHeader().setBackground(new Color(0,0,100));
tabmed.getTableHeader().setForeground(Color.white);
tabmed.setShowGrid(false);
tabmed.setShowVerticalLines(false);
   tabmed.setColumnSelectionAllowed(false);
    tabmed.setRowSelectionAllowed(false);
    tabmed.setSelectionBackground(Color.green);  
    tabmed.setRowHeight(24);
    jTable1.setRowHeight(24);
    
jTable1.getTableHeader().setBackground(new Color(0,0,100));
jTable1.getTableHeader().setForeground(Color.white);
jTable1.setShowGrid(false);
jTable1.setShowVerticalLines(false);
   jTable1.setColumnSelectionAllowed(false);
    jTable1.setRowSelectionAllowed(false);
    jTable1.setSelectionBackground(Color.green);  

    jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
    
 TableColumn col=jTable1.getColumnModel().getColumn(0);
 col.setPreferredWidth(40);
 col=jTable1.getColumnModel().getColumn(1);
 col.setPreferredWidth(400);
  col=jTable1.getColumnModel().getColumn(2);
 col.setPreferredWidth(180);
  col=jTable1.getColumnModel().getColumn(3);
 col.setPreferredWidth(90);
  col=jTable1.getColumnModel().getColumn(4);
 col.setPreferredWidth(80);
 col=jTable1.getColumnModel().getColumn(5);
 col.setPreferredWidth(80);
 pss.setVisible(false);
       
      //  db.go.filliste("select nom from produit", list1);
        // AutoCompleteDecorator.decorate(list1, prix);
        // m.getAllRows1("produit", "nom", med);
         //AutoCompleteDecorator.decorate(med);
        
      
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroup = new javax.swing.ButtonGroup();
        btngroupmoney = new javax.swing.ButtonGroup();
        jpop = new javax.swing.JPopupMenu();
        sup = new javax.swing.JMenuItem();
        prix = new javax.swing.JTextField();
        qte = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        panelcaisse = new javax.swing.JPanel();
        mony = new javax.swing.JLabel();
        total2 = new javax.swing.JLabel();
        recive = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        med1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        time = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        total1 = new javax.swing.JLabel();
        nameprodect = new javax.swing.JLabel();
        nlotproduit = new javax.swing.JLabel();
        expdate = new javax.swing.JLabel();
        nlotactive = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        expdate1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        expdate2 = new javax.swing.JLabel();
        tableuprix = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabmed = new javax.swing.JTable();
        nbordonance = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pss = new javax.swing.JTextField();
        date1 = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        radcentime = new javax.swing.JRadioButtonMenuItem();
        raddinare = new javax.swing.JRadioButtonMenuItem();
        cc = new javax.swing.JMenu();
        oui = new javax.swing.JRadioButtonMenuItem();
        non = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        sup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/delete.png"))); // NOI18N
        sup.setText("Supprimer");
        sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supActionPerformed(evt);
            }
        });
        jpop.add(sup);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(null);

        prix.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        prix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixActionPerformed(evt);
            }
        });
        prix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prixKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prixKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prixKeyTyped(evt);
            }
        });
        getContentPane().add(prix);
        prix.setBounds(20, 40, 163, 40);

        qte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qteKeyTyped(evt);
            }
        });
        getContentPane().add(qte);
        qte.setBounds(190, 40, 73, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel3.setText("Désignation");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 116, 20);

        panelcaisse.setBackground(new java.awt.Color(0, 0, 0));

        mony.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        mony.setForeground(new java.awt.Color(0, 153, 0));

        total2.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        total2.setForeground(new java.awt.Color(0, 153, 0));

        recive.setBackground(new java.awt.Color(0, 0, 0));
        recive.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        recive.setForeground(new java.awt.Color(0, 102, 0));
        recive.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reciveKeyReleased(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/ch30.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Payement");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Money");

        javax.swing.GroupLayout panelcaisseLayout = new javax.swing.GroupLayout(panelcaisse);
        panelcaisse.setLayout(panelcaisseLayout);
        panelcaisseLayout.setHorizontalGroup(
            panelcaisseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcaisseLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addGap(41, 41, 41)
                .addGroup(panelcaisseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(recive, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mony, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panelcaisseLayout.setVerticalGroup(
            panelcaisseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcaisseLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mony, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcaisseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        getContentPane().add(panelcaisse);
        panelcaisse.setBounds(300, 180, 550, 290);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Prix  Cts (PPA)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Quantitié");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 10, 73, 31);

        med1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        med1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                med1KeyReleased(evt);
            }
        });
        getContentPane().add(med1);
        med1.setBounds(20, 130, 880, 40);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Désignation", "Date EXP", "N° Lot", "Prix", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable1KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 170, 880, 370);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        time.setForeground(new java.awt.Color(0, 153, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("DA");

        total1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        total1.setForeground(new java.awt.Color(0, 153, 0));
        total1.setText("0.00");

        nameprodect.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameprodect.setForeground(new java.awt.Color(0, 153, 0));

        nlotproduit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nlotproduit.setForeground(new java.awt.Color(0, 153, 0));

        expdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        expdate.setForeground(new java.awt.Color(0, 153, 0));

        nlotactive.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nlotactive.setForeground(new java.awt.Color(0, 153, 0));
        nlotactive.setText("N° Lot:");

        time1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        time1.setForeground(new java.awt.Color(0, 153, 0));

        expdate1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        expdate1.setForeground(new java.awt.Color(0, 153, 0));
        expdate1.setText("EXP:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/ch30.png"))); // NOI18N

        expdate2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        expdate2.setForeground(new java.awt.Color(0, 153, 0));
        expdate2.setText("Prix:");

        tableuprix.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tableuprix.setForeground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(nameprodect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(60, 60, 60))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nlotactive, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nlotproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expdate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tableuprix, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)))
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(time1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(21, 21, 21))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameprodect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(total1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nlotproduit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nlotactive, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(time1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tableuprix, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(280, 20, 1080, 100);

        tabmed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tabmed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° ", "Désignation", "N° Lot", "Date EXP", "Prix", "Qte", "Sous Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabmed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabmedMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabmedMouseReleased(evt);
            }
        });
        tabmed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabmedKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabmed);
        if (tabmed.getColumnModel().getColumnCount() > 0) {
            tabmed.getColumnModel().getColumn(0).setResizable(false);
            tabmed.getColumnModel().getColumn(1).setResizable(false);
            tabmed.getColumnModel().getColumn(2).setResizable(false);
            tabmed.getColumnModel().getColumn(3).setResizable(false);
            tabmed.getColumnModel().getColumn(4).setResizable(false);
            tabmed.getColumnModel().getColumn(5).setResizable(false);
            tabmed.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 200, 880, 410);

        nbordonance.setEditable(false);
        nbordonance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(nbordonance);
        nbordonance.setBounds(1320, 0, 60, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/CRO_Health_Pill_in_Cart_04-15.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(780, 110, 640, 540);

        pss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pssActionPerformed(evt);
            }
        });
        pss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pssKeyReleased(evt);
            }
        });
        getContentPane().add(pss);
        pss.setBounds(1290, 170, 6, 20);

        date1.setDateFormatString("yyyy-MM-dd");
        date1.setEnabled(false);
        getContentPane().add(date1);
        date1.setBounds(290, 630, 130, 30);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(750, 620, 80, 90);

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 0));

        jMenu7.setText("             ");
        jMenuBar1.add(jMenu7);

        jMenu1.setText("                     ");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/ch1.png"))); // NOI18N
        jMenu5.setText("     Vente");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/ch8.png"))); // NOI18N
        jMenuItem2.setText("Vente au Comptoir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/ch9.png"))); // NOI18N
        jMenuItem4.setText("Vente Cnas/CasNos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/ch10.png"))); // NOI18N
        jMenuItem3.setText("Vente Credit Client");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuBar1.add(jMenu5);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/options-icon1.png"))); // NOI18N
        jMenu2.setText("Option");

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/euro-icon.png"))); // NOI18N
        jMenu4.setText("                       Type de prix");

        radcentime.setSelected(true);
        radcentime.setText("                Centime");
        radcentime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radcentimeActionPerformed(evt);
            }
        });
        jMenu4.add(radcentime);

        raddinare.setText("                Dinare");
        raddinare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raddinareActionPerformed(evt);
            }
        });
        jMenu4.add(raddinare);

        jMenu2.add(jMenu4);

        cc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/coins-700000-icon.png"))); // NOI18N
        cc.setText("Money");

        oui.setText("Oui");
        oui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouiActionPerformed(evt);
            }
        });
        cc.add(oui);

        non.setSelected(true);
        non.setText("Non");
        non.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonActionPerformed(evt);
            }
        });
        cc.add(non);

        jMenu2.add(cc);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/Ecommerce-Return-Purchase-icon.png"))); // NOI18N
        jMenu3.setText("Retour");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/Actions-view-list-details-icon.png"))); // NOI18N
        jMenu9.setText("Liste des Ventes");
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu9ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        jMenu6.setForeground(new java.awt.Color(0, 102, 0));
        jMenu6.setText("                                    Vente  Au Comptoire");
        jMenu6.setFocusable(false);
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuBar1.add(jMenu6);

        jMenu8.setForeground(new java.awt.Color(0, 102, 0));
        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/ch8.png"))); // NOI18N
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixActionPerformed

    private void prixKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prixKeyReleased
if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
    
prix.setText("");
qte.setText("");
med1.setText("");
}
 
        if(prix.getText().isEmpty()){if(evt.getKeyCode()==KeyEvent.VK_ENTER){
    jTable1.setVisible(false);
       jScrollPane2.setVisible(false);
            this.requestFocus();
 
 } }
        else{
        double marge;
        marge=Float.parseFloat(prix.getText());
       // DecimalFormat dtime = new DecimalFormat("0.00");
        if(radcentime.isSelected()){
        marge=marge/100;
      
      marge =Math.round(marge *100)/100.0;
     }
        if(raddinare.isSelected()){
        
        }
       m.getCustomRows("select id,nom,date,n_lot,prix,qte from stock where prix ='"+marge+"' AND qte>0 AND date>='"+d+"' ;", jTable1); 
       
       
       jTable1.setVisible(true);
       jScrollPane2.setVisible(true);
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           prix.setText(String.valueOf(marge));
       jTable1.requestFocus();
      
       if(jTable1.getRowCount()==1){
       int row=jTable1.getSelectedRow();
       id_stock=Integer.parseInt(jTable1.getValueAt(0, 0).toString());
String nm=jTable1.getValueAt(0, 1).toString();
nom=nm;
String date=jTable1.getValueAt(0, 2).toString();
String nlot=jTable1.getValueAt(0, 3).toString();
String p=jTable1.getValueAt(0, 4).toString();
 qtt=jTable1.getValueAt(0, 5).toString();
  m.getCustomRows("select nom from stock where id="+id_stock+" AND date < '"+HDate1+"' ;", jTable3); 
  if(jTable3.getRowCount()==1){
  tools.msgBox(" ATTENTION \n Ce Produit est de  date proche !!!\n date EXP: "+date);
  }
nameprodect.setText(nm);
nm=nm+" - "+date+" - "+nlot;
med1.setText(nm);
nlot1=nlot;
 nameprodect.setVisible(true);
        nlotactive.setVisible(true);
        nlotproduit.setVisible(true);
        expdate1.setVisible(true);
        expdate.setVisible(true);
        expdate2.setVisible(true);
        tableuprix.setVisible(true);
nlotproduit.setText(nlot);
expdate.setText(date);
tableuprix.setText(p);

qtestock=Integer.parseInt(jTable1.getValueAt(0, 5).toString());
double p1=Double.parseDouble(p);
//p1 =Float.parseFloat(dtime.format(p1));
 p1 =Math.round(p1 *100)/100.0;
prix.setText(String.valueOf(p1));
jTable1.setVisible(false);
jScrollPane2.setVisible(false);
qte.setText("1");
qte.selectAll();
qte.requestFocus();

       } }}
    // TODO add your handling code here:
    }//GEN-LAST:event_prixKeyReleased

    private void prixKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prixKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixKeyPressed

    private void prixKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prixKeyTyped
char c=evt.getKeyChar();
if(!((Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)||(c==KeyEvent.VK_PERIOD)||(c==KeyEvent.VK_ENTER))){
    getToolkit().beep();
    evt.consume();


}      // TODO add your handling code here:
    }//GEN-LAST:event_prixKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 btngroup.add(radcentime);
 btngroup.add(raddinare);
 btngroupmoney.add(oui);
 btngroupmoney.add(non);
        prix.requestFocus(); 
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void med1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med1KeyReleased
if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
    
prix.setText("");
qte.setText("");
med1.setText("");
} 
       // if(prix.getText()==null){m.getCustomRows("select nom_produit from produit where id=1;", jTable1);}
    
    
               m.getCustomRows("select id,nom,date,n_lot,prix,qte from stock where  qte>0 AND date>='"+d+"' AND nom LIKE '%"+med1.getText()+"%' ;", jTable1); 
      jTable1.setVisible(true);
       jScrollPane2.setVisible(true);
               if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jTable1.requestFocus();
                   if(jTable1.getRowCount()==1){
       int row=jTable1.getSelectedRow();
       id_stock=Integer.parseInt(jTable1.getValueAt(0, 0).toString());
String nm=jTable1.getValueAt(0, 1).toString();
nom=nm;
String date=jTable1.getValueAt(0, 2).toString();
String nlot=jTable1.getValueAt(0, 3).toString();
String p=jTable1.getValueAt(0, 4).toString();
 qtt=jTable1.getValueAt(0, 5).toString();
  m.getCustomRows("select nom from stock where prix ='"+p+"' AND qte>0 AND date < '"+HDate1+"' ;", jTable3); 
  if(jTable3.getRowCount()==1){
  tools.msgBox(" ATTENTION \n Ce Produit est de  date proche !!!\n date EXP: "+date);
  }
nameprodect.setText(nm);
nm=nm+" - "+date+" - "+nlot;
med1.setText(nm);
nlot1=nlot;
 nameprodect.setVisible(true);
        nlotactive.setVisible(true);
        nlotproduit.setVisible(true);
        expdate1.setVisible(true);
        expdate.setVisible(true);
        expdate2.setVisible(true);
        tableuprix.setVisible(true);
nlotproduit.setText(nlot);
expdate.setText(date);
tableuprix.setText(p);

qtestock=Integer.parseInt(jTable1.getValueAt(0, 5).toString());
double p1=Double.parseDouble(p);
//p1 =Float.parseFloat(dtime.format(p1));
 p1 =Math.round(p1 *100)/100.0;
prix.setText(String.valueOf(p1));
jTable1.setVisible(false);
jScrollPane2.setVisible(false);
qte.setText("1");
qte.selectAll();
qte.requestFocus();

       } 
        }
// TODO add your handling code here:
    }//GEN-LAST:event_med1KeyReleased

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

 if((evt.getKeyCode()==KeyEvent.VK_ENTER) &(tabmed.getRowCount()>0)){
if(tools.confirmMsg("L'ordonance est complete   ?"))
     {
   
    // this.jInternalFrame1.setEnabled(true);
panelcaisse.setVisible(true);
total2.setText(total1.getText());
nbordonance.setText(db.go.getAutoNumber("ordonanace", "nbr"));
prix.setText("");
qte.setText("");
med1.setText("");
o.getCustomRows("select id_ord,nom_produit,n_lot,date_exp,prix,qte,total from ordonanace where nbr='"+
         Integer.parseInt(nbordonance.getText())+"';", tabmed);

if(non.isSelected()){
        nameprodect.setVisible(false);
        nlotactive.setVisible(false);
        nlotproduit.setVisible(false);
        expdate1.setVisible(false);
        expdate.setVisible(false);
        expdate2.setVisible(false);
        tableuprix.setVisible(false);

        total1.setText("0.00");
        total2.setText("");
 prix.requestFocus();
 panelcaisse.setVisible(false);

}
if(oui.isSelected()){
recive.requestFocus();
}


     }
     else{
     prix.requestFocus();
     }
 } 
 if((evt.getKeyCode()==KeyEvent.VK_ENTER)&(tabmed.getRowCount()==0)&(!prix.getText().isEmpty() | !med1.getText().isEmpty()|!qte.getText().isEmpty())){
     tools.msgBox("L'ordonance est vide\n Remarque: entrer sur (+) pour ajouter le produit dans l'ordonance");
     prix.requestFocus();
     }// TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void qteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qteKeyReleased
if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
    
prix.setText("");
qte.setText("");
med1.setText("");
} 
  if(evt.getKeyCode()==KeyEvent.VK_ADD){
          String qtt2=o.getqteByid_stock(id_stock);
   if((Integer.parseInt(qte.getText())<1)|(Integer.parseInt(qte.getText())>(Integer.parseInt(qtt2)))){
  tools.confirmMsg("la quantité est insuffisante  \n Voulez-vous changer la valeur à 1 ?");
   qte.requestFocus();
   qte.setText("1");
   qte.selectAll();}
   else{
    
       o.setDate(time.getText());
   int n=Integer.parseInt(o.getAutoNumber());
    o.setId(n);
    o.setNbr(Integer.parseInt(nbordonance.getText()));
    o.setNom(nom);
    o.setPrix(Float.parseFloat(tableuprix.getText()));
    o.setTotal(Float.parseFloat(prix.getText())*Float.parseFloat(qte.getText()));
    o.setQte(Integer.parseInt(qte.getText()));
    o.setType("cash");
    o.setClient("");
    o.setN_lot(nlotproduit.getText());
    o.setDate_exp(expdate.getText());
    o.add();
    o.setQtestock(qtestock);
    o.setNom(nom);
    o.setN_lot(nlot1);
    o.setDate_exp(expdate.getText());
    o.setPrix(Float.parseFloat(tableuprix.getText()));
    o.update();
    o.getCustomRows("select id_ord,nom_produit,n_lot,date_exp,prix,qte,total from ordonanace where nbr='"+Integer.parseInt(nbordonance.getText())+"';", tabmed);// tools.msgBox("yes bb");
int count=tabmed.getRowCount();
float stock=0;
float som,q;
for(int i=0;i<count;i++)
{
  //  tools.msgBox("hello");
  q= Float.parseFloat(tabmed.getValueAt(i,6).toString());
stock=stock+q;   
}
total1.setText((String.valueOf(stock)));
//tools.clearText(this);
prix.setText("");
qte.setText("");
med1.setText("");
prix.requestFocus();
   } }// TODO add your handling code here:
    }//GEN-LAST:event_qteKeyReleased

    private void jTable1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyTyped

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
       
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){

            int row=jTable1.getSelectedRow();
            int rowc=jTable1.getRowCount();
            if(row==0){
                med1.setText(String.valueOf(rowc));
               // med1.requestFocus();
               
                      id_stock=Integer.parseInt(jTable1.getValueAt(rowc-1, 0).toString());
                String nm=jTable1.getValueAt(rowc-1, 1).toString();
                nom=nm;
            String date=jTable1.getValueAt(rowc-1, 2).toString();
            String nlot=jTable1.getValueAt(rowc-1, 3).toString();
            String p=jTable1.getValueAt(rowc-1, 4).toString();
              qtt=jTable1.getValueAt(0, 5).toString();
            nameprodect.setText(nm);
             m.getCustomRows("select nom from stock where id='"+id_stock+"' AND date < '"+HDate1+"' ;", jTable3); 
  if(jTable3.getRowCount()==1){
  tools.msgBox(" ATTENTION \n Ce Produit est de  date proche !!!\n date EXP: "+date);
  }
            nm=nm+" - "+date+" - "+nlot;
            med1.setText(nm);
            nlot1=nlot;
            nameprodect.setVisible(true);
        nlotactive.setVisible(true);
        nlotproduit.setVisible(true);
        expdate1.setVisible(true);
        expdate.setVisible(true);
        expdate2.setVisible(true);
        tableuprix.setVisible(true);
nlotproduit.setText(nlot);
expdate.setText(date);
tableuprix.setText(p);
            qtestock=Integer.parseInt(jTable1.getValueAt(rowc-1, 5).toString());
            prix.setText(p);
            jTable1.setVisible(false);
            jScrollPane2.setVisible(false);
            qte.setText("1");
            qte.requestFocus();
            qte.selectAll();
            }
            else{
                 id_stock=Integer.parseInt(jTable1.getValueAt(row-1, 0).toString());
            String nm=jTable1.getValueAt(row-1, 1).toString();
            nom=nm;
            String date=jTable1.getValueAt(row-1, 2).toString();
            String nlot=jTable1.getValueAt(row-1, 3).toString();
            String p=jTable1.getValueAt(row-1, 4).toString();
            qtt=jTable1.getValueAt(0, 5).toString();
            m.getCustomRows("select nom from stock where id='"+id_stock+"' AND date < '"+HDate1+"' ;", jTable3); 
  if(jTable3.getRowCount()==1){
  tools.msgBox(" ATTENTION \n Ce Produit est de  date proche !!!\n date EXP: "+date);
  }
            nameprodect.setText(nm);
            
            nm=nm+" - "+date+" - "+nlot;
            med1.setText(nm);
            nlot1=nlot;
            nameprodect.setVisible(true);
        nlotactive.setVisible(true);
        nlotproduit.setVisible(true);
        expdate1.setVisible(true);
        expdate.setVisible(true);
        expdate2.setVisible(true);
        tableuprix.setVisible(true);
nlotproduit.setText(nlot);
expdate.setText(date);
tableuprix.setText(p);
            qtestock=Integer.parseInt(jTable1.getValueAt(row-1, 5).toString());
            prix.setText(p);
            jTable1.setVisible(false);
            jScrollPane2.setVisible(false);
            qte.setText("1");
            qte.requestFocus();
            qte.selectAll();

        }
        } // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed

    }//GEN-LAST:event_jTable1KeyPressed

    private void radcentimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radcentimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radcentimeActionPerformed

    private void raddinareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raddinareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raddinareActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        tools.openForm(new frmVente());
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        tools.openForm(new frmVentechifa1());
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        tools.openForm(new frmVenteCredit());
        this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void nonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nonActionPerformed

    private void ouiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ouiActionPerformed

    private void pssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pssActionPerformed

    private void pssKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pssKeyReleased
      if(evt.getKeyCode()==KeyEvent.VK_ENTER){
      recive.requestFocus();
      }// TODO add your handling code here:
    }//GEN-LAST:event_pssKeyReleased

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
   // TODO add your handling code here:
            // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
    tools.openForm(new frmretour());
    // TODO add your handling code here:
            // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
    tools.openForm(new frmHome());
        this.dispose();   // TODO add your handling code here:
            // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
    tools.openForm(new frmretour());
        this.dispose();   // TODO add your handling code here:
            // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    private void qteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_qteKeyPressed

    private void qteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qteKeyTyped
char c=evt.getKeyChar();
if(!((Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)||(c==KeyEvent.VK_ENTER)||(c==KeyEvent.VK_ADD))){
    getToolkit().beep();
    evt.consume();
} 
if(c==KeyEvent.VK_ADD)
        {
            tools.msgBox(" yuuuuuuuuuuuuuuuuup");
        }// TODO add your handling code here:
    }//GEN-LAST:event_qteKeyTyped

    private void reciveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reciveKeyReleased
        if(recive.getText().isEmpty()){ mony.setText(String.valueOf(0-Float.parseFloat(total2.getText())));}
        else{    mony.setText(String.valueOf(Float.parseFloat(recive.getText())-Float.parseFloat(total2.getText())));}
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            nameprodect.setVisible(false);
            nlotactive.setVisible(false);
            nlotproduit.setVisible(false);
            expdate1.setVisible(false);
            expdate.setVisible(false);
            expdate2.setVisible(false);
            tableuprix.setVisible(false);

            total1.setText("0.00");
            total2.setText("");
            prix.requestFocus();
            panelcaisse.setVisible(false);
        }
    }//GEN-LAST:event_reciveKeyReleased

    private void tabmedMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabmedMouseReleased
 if(evt.isPopupTrigger()){
           
           jpop.show(this,evt.getXOnScreen(),evt.getYOnScreen());
    
   
   }        // TODO add your handling code here:
    }//GEN-LAST:event_tabmedMouseReleased

    private void supActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supActionPerformed
if(tools.confirmMsg("voulez vous vraiment supprimer Le produit dans l'ordonance ?"))
{ o.setId(id);
o.delete();

 String idd=(o.getqteByName(nom,nlot1,prim,d));
       // int qtt=Integer.parseInt(o.getqte(id));
       // int qttcmd=Integer.parseInt(o.getqtecmd(idd));
      //  float tot=Float.parseFloat(o.getprixtotal(id));
       // o.updateordonance(Integer.parseInt(qte.getText()),qtt, Float.parseFloat(total.getText()), tot,Integer.parseInt(id));
    
o.updatecmd(q,Integer.parseInt(idd),nlot1,d,prim,nom);
 o.getCustomRows("select id_ord,nom_produit,n_lot,date_exp,prix,qte,total from ordonanace where nbr='"+Integer.parseInt(nbordonance.getText())+"';", tabmed);// tools.msgBox("yes bb");
int count=tabmed.getRowCount();
float stock=0;
float som,q;
for(int i=0;i<count;i++)
{
  //  tools.msgBox("hello");
  q= Float.parseFloat(tabmed.getValueAt(i,6).toString());
stock=stock+q;   
}
total1.setText((String.valueOf(stock)));
//tools.clearText(this);
prix.setText("");
qte.setText("");
med1.setText("");
prix.requestFocus();

}
else
{

}// TODO add your handling code here:
    }//GEN-LAST:event_supActionPerformed

    private void tabmedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabmedMouseClicked
int count = tabmed.getSelectedRow();
id=Integer.parseInt(tabmed.getValueAt(count,0).toString());
nom=tabmed.getValueAt(count,1).toString();
nlot1=tabmed.getValueAt(count,2).toString();
d=tabmed.getValueAt(count,3).toString();
prim=Float.parseFloat(tabmed.getValueAt(count,4).toString());
q=Integer.parseInt(tabmed.getValueAt(count,5).toString());



// TODO add your handling code here:
    }//GEN-LAST:event_tabmedMouseClicked

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
    tools.openForm(new frmlistvent());    // TODO add your handling code here:
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jMenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu9ActionPerformed
tools.openForm(new frmlistvent());        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu9ActionPerformed

    private void tabmedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabmedKeyReleased
 if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
    if(tools.confirmMsg("voulez vous vraiment supprimer Le produit dans l'ordonance ?"))
{ o.setId(id);
o.delete();

 String idd=(o.getqteByName(nom,nlot1,prim,d));
       // int qtt=Integer.parseInt(o.getqte(id));
       // int qttcmd=Integer.parseInt(o.getqtecmd(idd));
      //  float tot=Float.parseFloat(o.getprixtotal(id));
       // o.updateordonance(Integer.parseInt(qte.getText()),qtt, Float.parseFloat(total.getText()), tot,Integer.parseInt(id));
    
o.updatecmd(q,Integer.parseInt(idd),nlot1,d,prim,nom);
 o.getCustomRows("select id_ord,nom_produit,n_lot,date_exp,prix,qte,total from ordonanace where nbr='"+Integer.parseInt(nbordonance.getText())+"';", tabmed);// tools.msgBox("yes bb");
int count=tabmed.getRowCount();
float stock=0;
float som,q;
for(int i=0;i<count;i++)
{
  //  tools.msgBox("hello");
  q= Float.parseFloat(tabmed.getValueAt(i,6).toString());
stock=stock+q;   
}
total1.setText((String.valueOf(stock)));
//tools.clearText(this);
prix.setText("");
qte.setText("");
med1.setText("");
prix.requestFocus();

}
else
{

}
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tabmedKeyReleased
 public void resetColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(240,240,240));
 }
  public void resetColorv(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(45,118,232));
 }
  public void setColorv(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(255,0,0));
 }
  public void setColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(0,128,0));
 }
  public void activethisframe()
  {
  this.setEnabled(true);
  prix.requestFocus();
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngroup;
    private javax.swing.ButtonGroup btngroupmoney;
    private javax.swing.JMenu cc;
    private com.toedter.calendar.JDateChooser date1;
    private javax.swing.JLabel expdate;
    private javax.swing.JLabel expdate1;
    private javax.swing.JLabel expdate2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JPopupMenu jpop;
    private javax.swing.JTextField med1;
    private javax.swing.JLabel mony;
    private javax.swing.JLabel nameprodect;
    private javax.swing.JTextField nbordonance;
    private javax.swing.JLabel nlotactive;
    private javax.swing.JLabel nlotproduit;
    private javax.swing.JRadioButtonMenuItem non;
    private javax.swing.JRadioButtonMenuItem oui;
    private javax.swing.JPanel panelcaisse;
    public static javax.swing.JTextField prix;
    private javax.swing.JTextField pss;
    private javax.swing.JTextField qte;
    private javax.swing.JRadioButtonMenuItem radcentime;
    private javax.swing.JRadioButtonMenuItem raddinare;
    private javax.swing.JTextField recive;
    private javax.swing.JMenuItem sup;
    private javax.swing.JLabel tableuprix;
    private javax.swing.JTable tabmed;
    private javax.swing.JLabel time;
    private javax.swing.JLabel time1;
    private javax.swing.JLabel total1;
    private javax.swing.JLabel total2;
    // End of variables declaration//GEN-END:variables
}
