/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import entity.midicament;
import entity.ordonance;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.TableColumn;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import work.tools;

/**
 *
 * @author choqib
 */
public class frmventeretour extends javax.swing.JFrame {
midicament m=new midicament();
 ordonance o=new ordonance();
 String d,qtt;
 String nlot1;
 int qtestock;
    /**
     * Creates new form frmVente
     */void showtime(){
     new Timer(0, new ActionListener(){
         @Override
         public void actionPerformed(ActionEvent e) {
Date d=new Date();
        SimpleDateFormat a = new SimpleDateFormat("yyyy-MM-dd");
        // time.setText(a.format(d)); 
        SimpleDateFormat a2 = new SimpleDateFormat("hh:mm:ss");
      //  time1.setText(a2.format(d));
         }
    
     
     }).start();
     
     }
    public frmventeretour() {
        
        this.setUndecorated(true);
        this.setAlwaysOnTop(false);
       this.setResizable(true);
        this.setVisible(true);
        
    
        initComponents();
        jTable1.setVisible(false);
        jScrollPane2.setVisible(false);
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        int x=(int) tk.getScreenSize().getWidth();
        int y=(int) tk.getScreenSize().getHeight();
        this.setSize(x,y );
        prix.requestFocus();
      //  panelcaisse.setVisible(false);
       Calendar clndr =Calendar.getInstance();
       d=String.valueOf(clndr.get(Calendar.YEAR))+"-"+String.valueOf(clndr.get(Calendar.MONTH))+"-"+
             String.valueOf(clndr.get(Calendar.DATE));
       showtime();
    
          
       nbordonance.setText(db.go.getAutoNumber("ordonanace", "nbr"));
           tabmed.getTableHeader().setBackground(new Color(0,0,100));
tabmed.getTableHeader().setForeground(Color.white);
tabmed.setShowGrid(false);
tabmed.setShowVerticalLines(false);
   tabmed.setColumnSelectionAllowed(false);
    tabmed.setRowSelectionAllowed(true);
    tabmed.setSelectionBackground(Color.green);  
    tabmed.setRowHeight(24);
    jTable1.setRowHeight(24);
    jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
 TableColumn col=jTable1.getColumnModel().getColumn(0);
 col.setPreferredWidth(400);
 col=jTable1.getColumnModel().getColumn(1);
 col.setPreferredWidth(180);
  col=jTable1.getColumnModel().getColumn(2);
 col.setPreferredWidth(100);
  col=jTable1.getColumnModel().getColumn(3);
 col.setPreferredWidth(95);
  col=jTable1.getColumnModel().getColumn(4);
 col.setPreferredWidth(100);
       
      //  db.go.filliste("select nom from produit", list1);
        // AutoCompleteDecorator.decorate(list1, prix);
        // m.getAllRows1("produit", "nom", med);
         //AutoCompleteDecorator.decorate(med);
        
      
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        prix = new javax.swing.JTextField();
        qte = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        med1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabmed = new javax.swing.JTable();
        nbordonance = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/back1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(100, 0, 97, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work/ch8.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(520, 10, 70, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Retour");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(580, 14, 240, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1380, 70);

        prix.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixActionPerformed(evt);
            }
        });
        prix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prixKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prixKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prixKeyTyped(evt);
            }
        });
        getContentPane().add(prix);
        prix.setBounds(20, 120, 163, 31);

        qte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qteKeyReleased(evt);
            }
        });
        getContentPane().add(qte);
        qte.setBounds(420, 120, 73, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel3.setText("Désignation");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 170, 116, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Date d'achat");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 100, 120, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Quantitié");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 90, 73, 31);

        med1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        med1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                med1KeyReleased(evt);
            }
        });
        getContentPane().add(med1);
        med1.setBounds(20, 200, 880, 30);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Désignation", "Date EXP", "N° Lot", "Prix", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable1KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 230, 880, 360);

        tabmed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tabmed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N° ", "Désignation", "Prix", "Qte", "Sous Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabmed);
        if (tabmed.getColumnModel().getColumnCount() > 0) {
            tabmed.getColumnModel().getColumn(0).setResizable(false);
            tabmed.getColumnModel().getColumn(1).setResizable(false);
            tabmed.getColumnModel().getColumn(2).setResizable(false);
            tabmed.getColumnModel().getColumn(3).setResizable(false);
            tabmed.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 270, 880, 480);

        nbordonance.setEditable(false);
        nbordonance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(nbordonance);
        nbordonance.setBounds(1320, 70, 60, 30);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(200, 120, 190, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Prix  Cts (PPA)");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 100, 120, 17);

        jMenu1.setText("                                                                                                            ");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Option");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Retour");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixActionPerformed

    private void prixKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prixKeyReleased

jTable1.getTableHeader().setBackground(new Color(0,0,100));
jTable1.getTableHeader().setForeground(Color.white);
jTable1.setShowGrid(false);
jTable1.setShowVerticalLines(false);
   jTable1.setColumnSelectionAllowed(false);
    jTable1.setRowSelectionAllowed(true);
    jTable1.setSelectionBackground(Color.green);  
        if(prix.getText().isEmpty()){if(evt.getKeyCode()==KeyEvent.VK_ENTER){
    this.requestFocus();
 
 } }
        else{
        float marge;
        marge=Float.parseFloat(prix.getText())/100;
     DecimalFormat dtime = new DecimalFormat("0.00"); 
     marge =Float.parseFloat(dtime.format(marge));
       m.getCustomRows("select nom_produit,exp,n_lot,pvent,qte from comande where pvent ='"+marge+"' AND qte>0;", jTable1); 
       jTable1.setVisible(true);
       jScrollPane2.setVisible(true);
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           prix.setText(String.valueOf(marge));
       jTable1.requestFocus();
      
       if(jTable1.getRowCount()==1){
       int row=jTable1.getSelectedRow();
String nm=jTable1.getValueAt(0, 0).toString();
String date=jTable1.getValueAt(0, 1).toString();
String nlot=jTable1.getValueAt(0, 2).toString();
String p=jTable1.getValueAt(0, 3).toString();
 qtt=jTable1.getValueAt(0, 4).toString();

nm=nm+" - "+date+" - "+nlot;
med1.setText(nm);
nlot1=nlot;


qtestock=Integer.parseInt(jTable1.getValueAt(0, 4).toString());
float p1=Float.parseFloat(p);
p1 =Float.parseFloat(dtime.format(p1));
prix.setText(String.valueOf(p1));
jTable1.setVisible(false);
jScrollPane2.setVisible(false);
qte.setText("1");
qte.selectAll();
qte.requestFocus();

       } }}
    // TODO add your handling code here:
    }//GEN-LAST:event_prixKeyReleased

    private void prixKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prixKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixKeyPressed

    private void prixKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prixKeyTyped
      // TODO add your handling code here:
    }//GEN-LAST:event_prixKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
prix.requestFocus(); 
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void med1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med1KeyReleased
        jTable1.getTableHeader().setBackground(new Color(0,0,100));
jTable1.getTableHeader().setForeground(Color.white);
jTable1.setShowGrid(false);
jTable1.setShowVerticalLines(false);
   jTable1.setColumnSelectionAllowed(false);
    jTable1.setRowSelectionAllowed(true);
    jTable1.setSelectionBackground(Color.green);  
    jTable1.setRowHeight(24);
       // if(prix.getText()==null){m.getCustomRows("select nom_produit from produit where id=1;", jTable1);}
    
        m.getCustomRows("select nom_produit,exp,n_lot,pvent,qte from comande where ppa='"+prix.getText()+"' AND qte >0 AND nom_produit LIKE '"+med1.getText()+"%';", jTable1);
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jTable1.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_med1KeyReleased

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
   if(evt.getKeyCode()==KeyEvent.VK_ADD){
     //  o.setDate(time.getText());
   int n=Integer.parseInt(o.getAutoNumber());
    o.setId(n);
    o.setNbr(Integer.parseInt(nbordonance.getText()));
    o.setNom(med1.getText());
    o.setPrix(Float.parseFloat(prix.getText()));
    o.setTotal(Float.parseFloat(prix.getText())*Float.parseFloat(qte.getText()));
    o.setQte(Integer.parseInt(qte.getText()));
    o.setType("cash");
    o.setClient("");
    o.add();
    o.setQtestock(qtestock);
    o.setNom(nlot1);
    o.update();
    o.getCustomRows("select nbr,nom_produit,prix,qte,total from ordonanace where nbr='"+Integer.parseInt(nbordonance.getText())+"';", tabmed);// tools.msgBox("yes bb");
int count=tabmed.getRowCount();
float stock=0;
float som,q;
for(int i=0;i<count;i++)
{
  //  tools.msgBox("hello");
  q= Float.parseFloat(tabmed.getValueAt(i,4).toString());
stock=stock+q;   
}

//tools.clearText(this);
prix.setText("");
qte.setText("");
med1.setText("");
prix.requestFocus();
   }   
 if(evt.getKeyCode()==KeyEvent.VK_ENTER){
 



 }   // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void qteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qteKeyReleased
if(evt.getKeyCode()==KeyEvent.VK_ENTER){
   // String qtt2=o.getValueByName(nlotproduit.getText());
 
}        // TODO add your handling code here:
    }//GEN-LAST:event_qteKeyReleased

    private void jTable1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyTyped

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){

            int row=jTable1.getSelectedRow();
            int rowc=jTable1.getRowCount();
            if(row==0){
                med1.setText(String.valueOf(rowc));
                med1.requestFocus();
                tools.msgBox("pfffffffffffff");
                String nm=jTable1.getValueAt(row-1, 0).toString();
            String date=jTable1.getValueAt(rowc-1, 1).toString();
            String nlot=jTable1.getValueAt(rowc-1, 2).toString();
            String p=jTable1.getValueAt(rowc-1, 3).toString();
              qtt=jTable1.getValueAt(0, 4).toString();

            nm=nm+" - "+date+" - "+nlot;
            med1.setText(nm);
            nlot1=nlot;
     
            qtestock=Integer.parseInt(jTable1.getValueAt(row-1, 4).toString());
            prix.setText(p);
            jTable1.setVisible(false);
            jScrollPane2.setVisible(false);
            qte.setText("1");
            qte.requestFocus();
            qte.selectAll();
            }
            else{
            String nm=jTable1.getValueAt(row-1, 0).toString();
            String date=jTable1.getValueAt(row-1, 1).toString();
            String nlot=jTable1.getValueAt(row-1, 2).toString();
            String p=jTable1.getValueAt(row-1, 3).toString();
            qtt=jTable1.getValueAt(0, 4).toString();
           
            nm=nm+" - "+date+" - "+nlot;
            med1.setText(nm);
            nlot1=nlot;
          
            qtestock=Integer.parseInt(jTable1.getValueAt(row-1, 4).toString());
            prix.setText(p);
            jTable1.setVisible(false);
            jScrollPane2.setVisible(false);
            qte.setText("1");
            qte.requestFocus();
            qte.selectAll();

        }
        } // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed

    }//GEN-LAST:event_jTable1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

tools.openForm(new frmHome());
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
 public void resetColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(240,240,240));
 }
  public void resetColorv(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(45,118,232));
 }
  public void setColorv(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(255,0,0));
 }
  public void setColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(0,128,0));
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmventeretour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmventeretour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmventeretour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmventeretour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmventeretour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField med1;
    private javax.swing.JTextField nbordonance;
    private javax.swing.JTextField prix;
    private javax.swing.JTextField qte;
    private javax.swing.JTable tabmed;
    // End of variables declaration//GEN-END:variables
}
