/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import entity.achat;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.table.TableColumn;

/**
 *
 * @author choqib
 */
public class frmvalidation extends javax.swing.JFrame {


    /**
     * Creates new form frmvalidation
     */
    achat a= new achat();

    
    public frmvalidation() {
         this.setUndecorated(false);
        this.setAlwaysOnTop(false);
       this.setResizable(false);
        this.setVisible(true);
        initComponents();
           Toolkit tk = Toolkit.getDefaultToolkit();
        int x=(int) tk.getScreenSize().getWidth();
        int y=(int) tk.getScreenSize().getHeight();
        this.setSize(1440, 750);
             tabcmd.setAutoResizeMode(tabcmd.AUTO_RESIZE_OFF);
 TableColumn col=tabcmd.getColumnModel().getColumn(0);
 col.setPreferredWidth(400);
 col=tabcmd.getColumnModel().getColumn(1);
 col.setPreferredWidth(100);
  col=tabcmd.getColumnModel().getColumn(2);
 col.setPreferredWidth(100);
  col=tabcmd.getColumnModel().getColumn(3);
 col.setPreferredWidth(100);
  col=tabcmd.getColumnModel().getColumn(4);
 col.setPreferredWidth(80);
  col=tabcmd.getColumnModel().getColumn(5);
 col.setPreferredWidth(150);
  col=tabcmd.getColumnModel().getColumn(6);
 col.setPreferredWidth(90);
  col=tabcmd.getColumnModel().getColumn(7);
 col.setPreferredWidth(100);
  col=tabcmd.getColumnModel().getColumn(8);
 col.setPreferredWidth(80);
  col=tabcmd.getColumnModel().getColumn(9);
 col.setPreferredWidth(50);
  tabcmd.getTableHeader().setBackground(new Color(0,0,100));
tabcmd.getTableHeader().setForeground(Color.white);
tabcmd.setShowGrid(true);
tabcmd.setShowVerticalLines(false);
tabcmd.setColumnSelectionAllowed(false);
tabcmd.setRowSelectionAllowed(true);
tabcmd.setSelectionBackground(Color.green);  
tabcmd.setRowHeight(24);
String s=save2.getText();
//a.getCustomRows("select nom_produit,n_lot,exp,ppa,pht,pvent,qte,shp,mge,ug from comande where nb_fact='"+s+"'", tabcmd);
a.getCustomRows("select nom_for,date_achat,type from comande where nb_fact='"+save2.getText()+"'", test);
fourn.setText(test.getValueAt(0,0).toString());
dateachat.setText(test.getValueAt(0,1).toString());
test.setVisible(false);
stest.setVisible(false);

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateachat = new javax.swing.JLabel();
        fo = new javax.swing.JLabel();
        fourn = new javax.swing.JLabel();
        fo1 = new javax.swing.JLabel();
        dd = new javax.swing.JScrollPane();
        tabcmd = new javax.swing.JTable();
        total = new javax.swing.JLabel();
        fo3 = new javax.swing.JLabel();
        stest = new javax.swing.JScrollPane();
        test = new javax.swing.JTable();
        save2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("N °                  :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(61, 11, 138, 33);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Date d'achat:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(61, 55, 138, 34);

        dateachat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(dateachat);
        dateachat.setBounds(210, 55, 342, 34);

        fo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fo.setText("Fournisseur:");
        getContentPane().add(fo);
        fo.setBounds(61, 95, 130, 34);

        fourn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(fourn);
        fourn.setBounds(205, 95, 347, 34);

        fo1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fo1.setText("Liste Des Achats:");
        getContentPane().add(fo1);
        fo1.setBounds(61, 135, 284, 46);

        dd.setBackground(new java.awt.Color(255, 255, 255));

        tabcmd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabcmd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Désignation", "N° Lot", "Date d'Exp", "PPA", "Prix Achat ", "Prix Vent", "QTE", "Shp", "Marge", "UG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabcmd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabcmdMouseClicked(evt);
            }
        });
        dd.setViewportView(tabcmd);
        if (tabcmd.getColumnModel().getColumnCount() > 0) {
            tabcmd.getColumnModel().getColumn(0).setResizable(false);
            tabcmd.getColumnModel().getColumn(1).setResizable(false);
            tabcmd.getColumnModel().getColumn(2).setResizable(false);
            tabcmd.getColumnModel().getColumn(3).setResizable(false);
            tabcmd.getColumnModel().getColumn(4).setResizable(false);
            tabcmd.getColumnModel().getColumn(5).setResizable(false);
            tabcmd.getColumnModel().getColumn(6).setResizable(false);
            tabcmd.getColumnModel().getColumn(7).setResizable(false);
            tabcmd.getColumnModel().getColumn(8).setResizable(false);
            tabcmd.getColumnModel().getColumn(9).setResizable(false);
        }

        getContentPane().add(dd);
        dd.setBounds(31, 192, 1256, 269);

        total.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        getContentPane().add(total);
        total.setBounds(660, 472, 502, 46);

        fo3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        fo3.setText("Tootal :");
        getContentPane().add(fo3);
        fo3.setBounds(553, 472, 101, 46);

        test.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        stest.setViewportView(test);

        getContentPane().add(stest);
        stest.setBounds(787, 34, 130, 90);

        save2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(save2);
        save2.setBounds(205, 11, 347, 33);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabcmdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabcmdMouseClicked
 

        // TODO add your handling code here:
    }//GEN-LAST:event_tabcmdMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmvalidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmvalidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmvalidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmvalidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmvalidation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel dateachat;
    private javax.swing.JScrollPane dd;
    private javax.swing.JLabel fo;
    private javax.swing.JLabel fo1;
    private javax.swing.JLabel fo3;
    public static javax.swing.JLabel fourn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel save2;
    private javax.swing.JScrollPane stest;
    public static javax.swing.JTable tabcmd;
    public static javax.swing.JTable test;
    public static javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
